{"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"The bounds rectangle, which describes the button’s location and size in its own coordinate system."}],"variants":[{"paths":["\/documentation\/lphud\/button\/bounds"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/lphud\/button\/bounds"]}],"metadata":{"symbolKind":"property","externalID":"c:@M@LPHUD@objc(cs)Button(py)bounds","navigatorTitle":[{"kind":"identifier","text":"bounds"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"bounds","kind":"identifier"},{"kind":"text","text":": "},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"}],"role":"symbol","roleHeading":"Instance Property","title":"bounds","modules":[{"name":"LPHUD"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"override","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"bounds","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Button"]]},"identifier":{"url":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Button\/bounds","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.LPHUD/documentation/LPHUD/Button":{"role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Button","url":"\/documentation\/lphud\/button","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Button"}],"navigatorTitle":[{"text":"Button","kind":"identifier"}],"title":"Button","kind":"symbol"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/Button/bounds":{"title":"bounds","url":"\/documentation\/lphud\/button\/bounds","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Button\/bounds","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"bounds"}],"abstract":[{"type":"text","text":"The bounds rectangle, which describes the button’s location and size in its own coordinate system."}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bounds","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"}],"type":"topic"},"doc://org.cocoapods.LPHUD/documentation/LPHUD":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","kind":"symbol","url":"\/documentation\/lphud","title":"LPHUD","role":"collection","type":"topic","abstract":[]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"bounds"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"bounds","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bounds"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1Button\/title","value":"Button"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1Button\/fragments","op":"replace","value":[{"text":"Button","kind":"identifier"}]},{"value":"bounds","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1Button~1bounds\/title"},{"value":[{"kind":"identifier","text":"bounds"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1Button~1bounds\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}