{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Button"]]},"abstract":[{"type":"text","text":"The natural size for the receiving view, considering only properties of the view itself."}],"sections":[],"variants":[{"paths":["\/documentation\/lphud\/button\/intrinsiccontentsize"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/lphud\/button\/intrinsiccontentsize"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"override"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"intrinsicContentSize","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Button\/intrinsicContentSize"},"metadata":{"externalID":"c:@M@LPHUD@objc(cs)Button(py)intrinsicContentSize","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"intrinsicContentSize","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"}],"roleHeading":"Instance Property","modules":[{"name":"LPHUD"}],"title":"intrinsicContentSize","role":"symbol","navigatorTitle":[{"text":"intrinsicContentSize","kind":"identifier"}]},"kind":"symbol","references":{"doc://org.cocoapods.LPHUD/documentation/LPHUD/Button/intrinsicContentSize":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"intrinsicContentSize","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"}],"url":"\/documentation\/lphud\/button\/intrinsiccontentsize","navigatorTitle":[{"kind":"identifier","text":"intrinsicContentSize"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Button\/intrinsicContentSize","kind":"symbol","type":"topic","title":"intrinsicContentSize","abstract":[{"type":"text","text":"The natural size for the receiving view, considering only properties of the view itself."}]},"doc://org.cocoapods.LPHUD/documentation/LPHUD":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","kind":"symbol","url":"\/documentation\/lphud","title":"LPHUD","role":"collection","type":"topic","abstract":[]},"doc://org.cocoapods.LPHUD/documentation/LPHUD/Button":{"role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Button","url":"\/documentation\/lphud\/button","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Button"}],"navigatorTitle":[{"text":"Button","kind":"identifier"}],"title":"Button","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"intrinsicContentSize","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"intrinsicContentSize","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier","text":"CGSize"},{"kind":"text","text":" "},{"text":"intrinsicContentSize","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1Button~1intrinsicContentSize\/title","value":"intrinsicContentSize"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1Button~1intrinsicContentSize\/fragments","value":[{"text":"intrinsicContentSize","kind":"identifier"}]},{"value":"Button","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1Button\/title"},{"op":"replace","value":[{"text":"Button","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1Button\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}