{"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"override"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isHighlighted"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}]}]}],"metadata":{"modules":[{"name":"LPHUD"}],"externalID":"c:@M@LPHUD@objc(cs)Button(py)highlighted","navigatorTitle":[{"kind":"identifier","text":"highlighted"}],"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isHighlighted"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"symbolKind":"property","role":"symbol","title":"isHighlighted"},"identifier":{"url":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Button\/isHighlighted","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Button"]]},"sections":[],"abstract":[{"type":"text","text":"A Boolean value indicating whether the control draws a highlight."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/lphud\/button\/ishighlighted"]},{"paths":["\/documentation\/lphud\/button\/ishighlighted"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://org.cocoapods.LPHUD/documentation/LPHUD/Button/isHighlighted":{"type":"topic","abstract":[{"text":"A Boolean value indicating whether the control draws a highlight.","type":"text"}],"url":"\/documentation\/lphud\/button\/ishighlighted","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isHighlighted"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"highlighted"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Button\/isHighlighted","title":"isHighlighted","role":"symbol"},"doc://org.cocoapods.LPHUD/documentation/LPHUD":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","kind":"symbol","url":"\/documentation\/lphud","title":"LPHUD","role":"collection","type":"topic","abstract":[]},"doc://org.cocoapods.LPHUD/documentation/LPHUD/Button":{"role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Button","url":"\/documentation\/lphud\/button","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Button"}],"navigatorTitle":[{"text":"Button","kind":"identifier"}],"title":"Button","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"highlighted","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"highlighted"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"getter","kind":"keyword"},{"text":"=","kind":"text"},{"kind":"identifier","text":"isHighlighted"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"highlighted"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1Button~1isHighlighted\/title","op":"replace","value":"highlighted"},{"op":"replace","value":[{"text":"highlighted","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1Button~1isHighlighted\/fragments"},{"value":"Button","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1Button\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1Button\/fragments","op":"replace","value":[{"kind":"identifier","text":"Button"}]}]}]}