{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD","doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ProgressView"]]},"identifier":{"url":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ProgressView\/bounds","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"override","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"bounds","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGRect","preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"sections":[],"metadata":{"role":"symbol","roleHeading":"Instance Property","modules":[{"name":"FlyHUD"}],"title":"bounds","navigatorTitle":[{"kind":"identifier","text":"bounds"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bounds"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"}],"symbolKind":"property","externalID":"c:@M@FlyHUD@objc(cs)ProgressView(py)bounds"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/flyhud\/progressview\/bounds"]},{"paths":["\/documentation\/flyhud\/progressview\/bounds"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","abstract":[{"text":"The bounds rectangle, which describes the view’s location and size in its own coordinate system.","type":"text"}],"references":{"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/ProgressView/bounds":{"navigatorTitle":[{"kind":"identifier","text":"bounds"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"bounds","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"}],"identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ProgressView\/bounds","type":"topic","abstract":[{"text":"The bounds rectangle, which describes the view’s location and size in its own coordinate system.","type":"text"}],"url":"\/documentation\/flyhud\/progressview\/bounds","role":"symbol","kind":"symbol","title":"bounds"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/ProgressView":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"ProgressView"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ProgressView"}],"identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ProgressView","abstract":[{"type":"text","text":"A view that depicts the progress of a task over time."}],"title":"ProgressView","url":"\/documentation\/flyhud\/progressview"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD":{"type":"topic","identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD","kind":"symbol","abstract":[],"url":"\/documentation\/flyhud","role":"collection","title":"FlyHUD"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"bounds"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","value":[{"text":"bounds","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"kind":"text","text":" "},{"kind":"identifier","text":"bounds"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"bounds","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1ProgressView~1bounds\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1ProgressView~1bounds\/fragments","op":"replace","value":[{"text":"bounds","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1ProgressView\/title","op":"replace","value":"ProgressView"},{"value":[{"kind":"identifier","text":"ProgressView"}],"path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1ProgressView\/fragments","op":"replace"}]}]}