{"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ProgressView\/intrinsicContentSize","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"intrinsicContentSize","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"intrinsicContentSize"}],"externalID":"c:@M@FlyHUD@objc(cs)ProgressView(py)intrinsicContentSize","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"intrinsicContentSize","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"role":"symbol","roleHeading":"Instance Property","symbolKind":"property","modules":[{"name":"FlyHUD"}],"title":"intrinsicContentSize"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD","doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ProgressView"]]},"abstract":[{"text":"The natural size for the receiving view, considering only properties of the view itself.","type":"text"}],"variants":[{"paths":["\/documentation\/flyhud\/progressview\/intrinsiccontentsize"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/flyhud\/progressview\/intrinsiccontentsize"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/ProgressView":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"ProgressView"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ProgressView"}],"identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ProgressView","abstract":[{"type":"text","text":"A view that depicts the progress of a task over time."}],"title":"ProgressView","url":"\/documentation\/flyhud\/progressview"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/ProgressView/intrinsicContentSize":{"type":"topic","url":"\/documentation\/flyhud\/progressview\/intrinsiccontentsize","abstract":[{"type":"text","text":"The natural size for the receiving view, considering only properties of the view itself."}],"navigatorTitle":[{"text":"intrinsicContentSize","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ProgressView\/intrinsicContentSize","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"intrinsicContentSize"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"role":"symbol","title":"intrinsicContentSize"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD":{"type":"topic","identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD","kind":"symbol","abstract":[],"url":"\/documentation\/flyhud","role":"collection","title":"FlyHUD"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"intrinsicContentSize","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","value":[{"text":"intrinsicContentSize","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":" "},{"text":"intrinsicContentSize","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"ProgressView","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1ProgressView\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1ProgressView\/fragments","value":[{"text":"ProgressView","kind":"identifier"}]},{"value":"intrinsicContentSize","path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1ProgressView~1intrinsicContentSize\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"intrinsicContentSize"}],"path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1ProgressView~1intrinsicContentSize\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}