{"identifier":{"url":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BackgroundView\/intrinsicContentSize","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Instance Property","title":"intrinsicContentSize","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"intrinsicContentSize","kind":"identifier"},{"kind":"text","text":": "},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"}],"symbolKind":"property","modules":[{"name":"LPHUD"}],"externalID":"c:@M@LPHUD@objc(cs)BackgroundView(py)intrinsicContentSize","navigatorTitle":[{"kind":"identifier","text":"intrinsicContentSize"}]},"abstract":[{"type":"text","text":"The natural size for the receiving view, considering only properties of the view itself."}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"override"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"intrinsicContentSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BackgroundView"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/lphud\/backgroundview\/intrinsiccontentsize"]},{"paths":["\/documentation\/lphud\/backgroundview\/intrinsiccontentsize"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://org.cocoapods.LPHUD/documentation/LPHUD":{"role":"collection","kind":"symbol","abstract":[],"title":"LPHUD","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","type":"topic","url":"\/documentation\/lphud"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/BackgroundView/intrinsicContentSize":{"kind":"symbol","title":"intrinsicContentSize","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"intrinsicContentSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"}],"url":"\/documentation\/lphud\/backgroundview\/intrinsiccontentsize","abstract":[{"type":"text","text":"The natural size for the receiving view, considering only properties of the view itself."}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BackgroundView\/intrinsicContentSize","navigatorTitle":[{"text":"intrinsicContentSize","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/BackgroundView":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BackgroundView","url":"\/documentation\/lphud\/backgroundview","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"BackgroundView"}],"title":"BackgroundView","abstract":[{"type":"text","text":"The view to use as the background of the HUD."},{"text":" ","type":"text"},{"type":"text","text":"HUD adds the background view as a subview behind all other views and uses its current frame location."}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BackgroundView"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","value":"intrinsicContentSize","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"intrinsicContentSize"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"CGSize","preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"intrinsicContentSize","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1BackgroundView~1intrinsicContentSize\/title","value":"intrinsicContentSize"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1BackgroundView~1intrinsicContentSize\/fragments","value":[{"kind":"identifier","text":"intrinsicContentSize"}]},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1BackgroundView\/title","value":"BackgroundView","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1BackgroundView\/fragments","value":[{"text":"BackgroundView","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}