{"kind":"symbol","abstract":[{"type":"text","text":"A view that shows that a task is in progress."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ActivityIndicatorView\/init(style:size:populator:)","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ActivityIndicatorView\/init(styleable:size:populator:)"]},{"identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ActivityIndicatorView\/bounds","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ActivityIndicatorView\/color","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ActivityIndicatorView\/hidesWhenStopped","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ActivityIndicatorView\/intrinsicContentSize","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ActivityIndicatorView\/isAnimating","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ActivityIndicatorView\/lineWidth","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ActivityIndicatorView\/style-swift.property","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ActivityIndicatorView\/trackColor"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ActivityIndicatorView\/commonInit()","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ActivityIndicatorView\/didMoveToWindow()","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ActivityIndicatorView\/startAnimating()","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ActivityIndicatorView\/stopAnimating()","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ActivityIndicatorView\/traitCollectionDidChange(_:)"]},{"identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ActivityIndicatorView\/Style-swift.enum"],"title":"Enumerations"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ActivityIndicatorView","kind":"identifier"}],"languages":["swift"]}]},{"kind":"content","content":[{"text":"Overview","anchor":"overview","level":2,"type":"heading"},{"name":"Note","content":[{"inlineContent":[{"type":"text","text":"You control when an activity indicator animates by calling the startAnimating() and stopAnimating()"},{"type":"text","text":" "},{"type":"text","text":"methods. To automatically hide the activity indicator when animation stops, set the hidesWhenStopped"},{"type":"text","text":" "},{"text":"property to true. You can set the color of the activity indicator by using the color property.","type":"text"}],"type":"paragraph"}],"type":"aside","style":"note"}]}],"sections":[],"metadata":{"modules":[{"name":"LPHUD"}],"navigatorTitle":[{"kind":"identifier","text":"ActivityIndicatorView"}],"title":"ActivityIndicatorView","symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ActivityIndicatorView"}],"roleHeading":"Class","role":"symbol","externalID":"c:@M@LPHUD@objc(cs)ActivityIndicatorView"},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BaseView"],"type":"inheritsFrom"},{"title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ActivityIndicatorViewable","doc:\/\/org.cocoapods.LPHUD\/objc(pl)NSCoding","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUDExtended","doc:\/\/org.cocoapods.LPHUD\/objc(pl)NSObject","doc:\/\/org.cocoapods.LPHUD\/objc(pl)CALayerDelegate","doc:\/\/org.cocoapods.LPHUD\/s7CVarArgP","doc:\/\/org.cocoapods.LPHUD\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.LPHUD\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.LPHUD\/SQ","doc:\/\/org.cocoapods.LPHUD\/SH","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIAccessibilityIdentification","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIAppearance","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UICoordinateSpace","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIDynamicItem","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIFocusItem","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIFocusItemContainer","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UILargeContentViewerItem","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.LPHUD\/5UIKit23UITraitChangeObservableP","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ActivityIndicatorView","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD"]]},"variants":[{"paths":["\/documentation\/lphud\/activityindicatorview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/lphud\/activityindicatorview"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.LPHUD/documentation/LPHUD/ActivityIndicatorView/init(styleable:size:populator:)":{"kind":"symbol","abstract":[{"text":"Creates an activity indicator view with the specified style.","type":"text"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ActivityIndicatorView\/init(styleable:size:populator:)","title":"init(styleable:size:populator:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"styleable"},{"kind":"text","text":": "},{"text":"ActivityIndicatorViewStyleable","kind":"typeIdentifier","preciseIdentifier":"s:5LPHUD30ActivityIndicatorViewStyleableP"},{"kind":"text","text":", "},{"kind":"externalParam","text":"size"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"},{"kind":"text","text":", "},{"text":"populator","kind":"externalParam"},{"text":": ((","kind":"text"},{"preciseIdentifier":"c:@M@LPHUD@objc(cs)ActivityIndicatorView","text":"ActivityIndicatorView","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"url":"\/documentation\/lphud\/activityindicatorview\/init(styleable:size:populator:)","role":"symbol"},"doc://org.cocoapods.LPHUD/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIResponderStandardEditActions","title":"UIKit.UIResponderStandardEditActions"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ActivityIndicatorViewable":{"abstract":[{"type":"text","text":"A view that shows that a task is in progress."}],"url":"\/documentation\/lphud\/activityindicatorviewable","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ActivityIndicatorViewable","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ActivityIndicatorViewable"}],"title":"ActivityIndicatorViewable","type":"topic","role":"symbol","navigatorTitle":[{"text":"ActivityIndicatorViewable","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ActivityIndicatorView/isAnimating":{"url":"\/documentation\/lphud\/activityindicatorview\/isanimating","title":"isAnimating","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isAnimating","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ActivityIndicatorView\/isAnimating","abstract":[{"text":"A Boolean value indicating whether the activity indicator is currently running its animation.","type":"text"}]},"doc://org.cocoapods.LPHUD/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.LPHUD\/SH"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ActivityIndicatorView/Style-swift.enum":{"url":"\/documentation\/lphud\/activityindicatorview\/style-swift.enum","kind":"symbol","abstract":[{"text":"The visual style of the activity indicator.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ActivityIndicatorView\/Style-swift.enum","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Style"}],"navigatorTitle":[{"text":"Style","kind":"identifier"}],"title":"ActivityIndicatorView.Style","type":"topic"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ActivityIndicatorView/initWithCoder:":{"abstract":[],"url":"\/documentation\/lphud\/activityindicatorview\/initwithcoder:","title":"initWithCoder:","type":"topic","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ActivityIndicatorView\/initWithCoder:","kind":"symbol","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithCoder:","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}]},"doc://org.cocoapods.LPHUD/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIUserActivityRestoring"},"doc://org.cocoapods.LPHUD/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UITraitEnvironment"},"doc://org.cocoapods.LPHUD/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.LPHUD\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.LPHUD/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.LPHUD\/s23CustomStringConvertibleP"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ActivityIndicatorView/style-swift.property":{"url":"\/documentation\/lphud\/activityindicatorview\/style-swift.property","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ActivityIndicatorView\/style-swift.property","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"style","kind":"identifier"},{"kind":"text","text":": "},{"text":"ActivityIndicatorViewStyleable","preciseIdentifier":"s:5LPHUD30ActivityIndicatorViewStyleableP","kind":"typeIdentifier"}],"role":"symbol","kind":"symbol","title":"style","abstract":[{"type":"text","text":"The basic appearance of the activity indicator view. The value of this property is a constant that specifies the style of the activity indicator view."}]},"doc://org.cocoapods.LPHUD/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIAppearance"},"doc://org.cocoapods.LPHUD/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIFocusItemContainer"},"doc://org.cocoapods.LPHUD/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UICoordinateSpace"},"doc://org.cocoapods.LPHUD/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)NSObject"},"doc://org.cocoapods.LPHUD/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIAccessibilityIdentification"},"doc://org.cocoapods.LPHUD/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UILargeContentViewerItem"},"doc://org.cocoapods.LPHUD/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.LPHUD\/s7CVarArgP"},"doc://org.cocoapods.LPHUD/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","title":"UIKit.UITraitChangeObservable","identifier":"doc:\/\/org.cocoapods.LPHUD\/5UIKit23UITraitChangeObservableP"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ActivityIndicatorView/stopAnimating()":{"kind":"symbol","abstract":[{"type":"text","text":"Stops the animation of the activity indicator."}],"type":"topic","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ActivityIndicatorView\/stopAnimating()","title":"stopAnimating()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stopAnimating","kind":"identifier"},{"text":"()","kind":"text"}],"url":"\/documentation\/lphud\/activityindicatorview\/stopanimating()","role":"symbol"},"doc://org.cocoapods.LPHUD/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)NSCoding"},"doc://org.cocoapods.LPHUD/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.LPHUD\/SQ"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ActivityIndicatorView/didMoveToWindow()":{"type":"topic","title":"didMoveToWindow()","kind":"symbol","url":"\/documentation\/lphud\/activityindicatorview\/didmovetowindow()","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ActivityIndicatorView\/didMoveToWindow()","abstract":[],"role":"symbol","navigatorTitle":[{"text":"didMoveToWindow","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"didMoveToWindow","kind":"identifier"},{"kind":"text","text":"()"}]},"doc://org.cocoapods.LPHUD/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIPasteConfigurationSupporting"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ActivityIndicatorView/bounds":{"kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ActivityIndicatorView\/bounds","navigatorTitle":[{"text":"bounds","kind":"identifier"}],"title":"bounds","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bounds","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGRect","preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier"}],"url":"\/documentation\/lphud\/activityindicatorview\/bounds","role":"symbol"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ActivityIndicatorView/hidesWhenStopped":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ActivityIndicatorView\/hidesWhenStopped","title":"hidesWhenStopped","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hidesWhenStopped"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"A Boolean value that controls whether the activity indicator is hidden when the animation is stopped."}],"url":"\/documentation\/lphud\/activityindicatorview\/hideswhenstopped"},"doc://org.cocoapods.LPHUD/objc(pl)UIFocusEnvironment":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIFocusEnvironment","type":"unresolvable","title":"UIKit.UIFocusEnvironment"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ActivityIndicatorView":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ActivityIndicatorView"}],"title":"ActivityIndicatorView","navigatorTitle":[{"text":"ActivityIndicatorView","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A view that shows that a task is in progress."}],"url":"\/documentation\/lphud\/activityindicatorview","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ActivityIndicatorView","role":"symbol"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUDExtended":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HUDExtended"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUDExtended","abstract":[{"text":"Protocol describing the ","type":"text"},{"code":"h","type":"codeVoice"},{"text":" extension points for HUD extended types.","type":"text"}],"type":"topic","url":"\/documentation\/lphud\/hudextended","title":"HUDExtended","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HUDExtended"}]},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ActivityIndicatorView/initWithFrame:":{"type":"topic","abstract":[],"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithFrame:"}],"navigatorTitle":[{"text":"initWithFrame:","kind":"identifier"}],"url":"\/documentation\/lphud\/activityindicatorview\/initwithframe:","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ActivityIndicatorView\/initWithFrame:","title":"initWithFrame:","role":"symbol","kind":"symbol"},"doc://org.cocoapods.LPHUD/objc(pl)UIAppearanceContainer":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIAppearanceContainer","type":"unresolvable","title":"UIKit.UIAppearanceContainer"},"doc://org.cocoapods.LPHUD/objc(pl)UIFocusItem":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIFocusItem","type":"unresolvable","title":"UIKit.UIFocusItem"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ActivityIndicatorView/traitCollectionDidChange(_:)":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"traitCollectionDidChange"},{"text":"(","kind":"text"},{"text":"UITraitCollection","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITraitCollection"},{"text":"?)","kind":"text"}],"kind":"symbol","url":"\/documentation\/lphud\/activityindicatorview\/traitcollectiondidchange(_:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"traitCollectionDidChange:"}],"title":"traitCollectionDidChange(_:)","abstract":[],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ActivityIndicatorView\/traitCollectionDidChange(_:)"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ActivityIndicatorView/trackColor":{"abstract":[{"type":"text","text":"The track color of the activity indicator."}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackColor"},{"kind":"text","text":": "},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ActivityIndicatorView\/trackColor","url":"\/documentation\/lphud\/activityindicatorview\/trackcolor","title":"trackColor"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ActivityIndicatorView/color":{"url":"\/documentation\/lphud\/activityindicatorview\/color","title":"color","kind":"symbol","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ActivityIndicatorView\/color","abstract":[{"text":"The color of the activity indicator.","type":"text"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"color","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"text":"!","kind":"text"}],"type":"topic"},"doc://org.cocoapods.LPHUD/objc(pl)CALayerDelegate":{"title":"QuartzCore.CALayerDelegate","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)CALayerDelegate"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ActivityIndicatorView/intrinsicContentSize":{"url":"\/documentation\/lphud\/activityindicatorview\/intrinsiccontentsize","abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ActivityIndicatorView\/intrinsicContentSize","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"intrinsicContentSize"}],"title":"intrinsicContentSize","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"intrinsicContentSize","kind":"identifier"},{"kind":"text","text":": "},{"text":"CGSize","preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier"}]},"doc://org.cocoapods.LPHUD/documentation/LPHUD":{"abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","url":"\/documentation\/lphud","kind":"symbol","title":"LPHUD"},"doc://org.cocoapods.LPHUD/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIPopoverPresentationControllerSourceItem","title":"UIKit.UIPopoverPresentationControllerSourceItem"},"doc://org.cocoapods.LPHUD/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding"},"doc://org.cocoapods.LPHUD/objc(pl)UIDynamicItem":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIDynamicItem","title":"UIKit.UIDynamicItem"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ActivityIndicatorView/lineWidth":{"url":"\/documentation\/lphud\/activityindicatorview\/linewidth","abstract":[{"type":"text","text":"The line width of the activity indicator."}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"lineWidth","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ActivityIndicatorView\/lineWidth","title":"lineWidth"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ActivityIndicatorView/startAnimating()":{"url":"\/documentation\/lphud\/activityindicatorview\/startanimating()","title":"startAnimating()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"startAnimating","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ActivityIndicatorView\/startAnimating()","abstract":[{"text":"Starts the animation of the activity indicator.","type":"text"}]},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ActivityIndicatorView/init(style:size:populator:)":{"type":"topic","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"style","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Style","preciseIdentifier":"s:5LPHUD21ActivityIndicatorViewC5StyleO"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"size"},{"text":": ","kind":"text"},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":", "},{"kind":"externalParam","text":"populator"},{"kind":"text","text":": (("},{"text":"ActivityIndicatorView","kind":"typeIdentifier","preciseIdentifier":"c:@M@LPHUD@objc(cs)ActivityIndicatorView"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")?)","kind":"text"}],"url":"\/documentation\/lphud\/activityindicatorview\/init(style:size:populator:)","title":"init(style:size:populator:)","abstract":[{"type":"text","text":"Creates an activity indicator view with the specified style."}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ActivityIndicatorView\/init(style:size:populator:)"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ActivityIndicatorView/commonInit()":{"role":"symbol","title":"commonInit()","kind":"symbol","abstract":[{"type":"text","text":"The default implementation of this method does nothing."},{"type":"text","text":" "},{"text":"Subclasses can override it to perform additional actions after superview initialization.","type":"text"}],"url":"\/documentation\/lphud\/activityindicatorview\/commoninit()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"commonInit"},{"text":"()","kind":"text"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ActivityIndicatorView\/commonInit()"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/BaseView":{"kind":"symbol","url":"\/documentation\/lphud\/baseview","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"BaseView","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"BaseView"}],"type":"topic","abstract":[{"text":"A base view only provides one ","type":"text"},{"type":"codeVoice","code":"commonInit"},{"type":"text","text":" method."}],"title":"BaseView","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BaseView","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"value":"ActivityIndicatorView","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"ActivityIndicatorView","kind":"identifier"}]},{"value":[{"text":"ActivityIndicatorView","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ActivityIndicatorView\/bounds","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ActivityIndicatorView\/intrinsicContentSize"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ActivityIndicatorView\/didMoveToWindow()","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ActivityIndicatorView\/initWithCoder:","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ActivityIndicatorView\/initWithFrame:","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ActivityIndicatorView\/traitCollectionDidChange(_:)"]}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BaseView"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"}],"op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ActivityIndicatorView","kind":"identifier"},{"text":" : ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BaseView","preciseIdentifier":"c:@M@LPHUD@objc(cs)BaseView","text":"BaseView","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ActivityIndicatorView~1didMoveToWindow()\/title","value":"didMoveToWindow"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ActivityIndicatorView~1didMoveToWindow()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"didMoveToWindow"}]},{"op":"replace","value":"bounds","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ActivityIndicatorView~1bounds\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ActivityIndicatorView~1bounds\/fragments","value":[{"kind":"identifier","text":"bounds"}],"op":"replace"},{"op":"replace","value":"ActivityIndicatorView","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ActivityIndicatorView\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ActivityIndicatorView\/fragments","op":"replace","value":[{"text":"ActivityIndicatorView","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ActivityIndicatorView~1traitCollectionDidChange(_:)\/title","value":"traitCollectionDidChange:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"traitCollectionDidChange:"}],"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ActivityIndicatorView~1traitCollectionDidChange(_:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ActivityIndicatorView~1intrinsicContentSize\/title","value":"intrinsicContentSize","op":"replace"},{"value":[{"text":"intrinsicContentSize","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ActivityIndicatorView~1intrinsicContentSize\/fragments"},{"op":"replace","value":"BaseView","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1BaseView\/title"},{"value":[{"text":"BaseView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1BaseView\/fragments"}]}]}