{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/lphud\/progressview"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/lphud\/progressview"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView"},"metadata":{"navigatorTitle":[{"text":"ProgressView","kind":"identifier"}],"symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ProgressView"}],"role":"symbol","externalID":"c:@M@LPHUD@objc(cs)ProgressView","title":"ProgressView","modules":[{"name":"LPHUD"}],"roleHeading":"Class"},"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BaseView"],"title":"Inherits From"},{"title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/DisplayLinkDelegate","doc:\/\/org.cocoapods.LPHUD\/objc(pl)NSCoding","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUDExtended","doc:\/\/org.cocoapods.LPHUD\/objc(pl)NSObject","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressViewable","doc:\/\/org.cocoapods.LPHUD\/objc(pl)CALayerDelegate","doc:\/\/org.cocoapods.LPHUD\/s7CVarArgP","doc:\/\/org.cocoapods.LPHUD\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.LPHUD\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.LPHUD\/SQ","doc:\/\/org.cocoapods.LPHUD\/SH","doc:\/\/org.cocoapods.LPHUD\/s8SendableP","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIAccessibilityIdentification","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIAppearance","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UICoordinateSpace","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIDynamicItem","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIFocusItem","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIFocusItemContainer","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UILargeContentViewerItem","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.LPHUD\/5UIKit23UITraitChangeObservableP","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIUserActivityRestoring"],"type":"conformsTo","kind":"relationships"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"A view that depicts the progress of a task over time."}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView\/init(style:size:populator:)","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView\/init(styleable:size:populator:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView\/alpha","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView\/bounds","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView\/intrinsicContentSize","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView\/isHidden","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView\/isLabelEnabled","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView\/labelFont","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView\/lineWidth","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView\/observedProgress","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView\/progress","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView\/progressTintColor","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView\/style-swift.property","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView\/trackTintColor"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView\/commonInit()","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView\/didMoveToSuperview()","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView\/didMoveToWindow()","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView\/draw(_:)","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView\/updateScreenInDisplayLink()"]},{"identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView\/Style-swift.enum"],"title":"Enumerations"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ProgressView","kind":"identifier"}]}]},{"kind":"content","content":[{"level":2,"anchor":"overview","text":"Overview","type":"heading"},{"inlineContent":[{"text":"The ProgressView class provides properties for managing the style of the progress","type":"text"},{"text":" ","type":"text"},{"text":"bar and for getting and setting values that are pinned to the progress of a task.","type":"text"}],"type":"paragraph"},{"type":"aside","name":"Note","style":"note","content":[{"type":"paragraph","inlineContent":[{"text":"For an indeterminate progress indicator — or a “spinner” — use an instance of the ActivityIndicatorView class.","type":"text"}]}]}]}],"sections":[],"references":{"doc://org.cocoapods.LPHUD/documentation/LPHUD/ProgressView/draw(_:)":{"kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView\/draw(_:)","navigatorTitle":[{"text":"drawRect:","kind":"identifier"}],"title":"draw(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"draw","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"text":")","kind":"text"}],"url":"\/documentation\/lphud\/progressview\/draw(_:)","role":"symbol"},"doc://org.cocoapods.LPHUD/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/s7CVarArgP","title":"Swift.CVarArg"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ProgressView/updateScreenInDisplayLink()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"updateScreenInDisplayLink","kind":"identifier"},{"kind":"text","text":"()"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView\/updateScreenInDisplayLink()","abstract":[{"text":"Refreshing the progress only every frame draw.","type":"text"}],"url":"\/documentation\/lphud\/progressview\/updatescreenindisplaylink()","title":"updateScreenInDisplayLink()","type":"topic"},"doc://org.cocoapods.LPHUD/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIPopoverPresentationControllerSourceItem","title":"UIKit.UIPopoverPresentationControllerSourceItem"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/DisplayLinkDelegate":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/DisplayLinkDelegate","abstract":[{"type":"text","text":"The methods adopted by the object that allows your app to synchronize its drawing to the refresh rate of the display."}],"title":"DisplayLinkDelegate","url":"\/documentation\/lphud\/displaylinkdelegate","kind":"symbol","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"DisplayLinkDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DisplayLinkDelegate"}]},"doc://org.cocoapods.LPHUD/documentation/LPHUD/BaseView":{"kind":"symbol","url":"\/documentation\/lphud\/baseview","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"BaseView","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"BaseView"}],"type":"topic","abstract":[{"text":"A base view only provides one ","type":"text"},{"type":"codeVoice","code":"commonInit"},{"type":"text","text":" method."}],"title":"BaseView","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BaseView","role":"symbol"},"doc://org.cocoapods.LPHUD/objc(pl)UIAppearanceContainer":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIAppearanceContainer","title":"UIKit.UIAppearanceContainer"},"doc://org.cocoapods.LPHUD/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UILargeContentViewerItem","title":"UIKit.UILargeContentViewerItem"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ProgressView/style-swift.property":{"abstract":[{"type":"text","text":"The current graphical style of the progress view. The value of this property is a constant that specifies the style of the progress view."}],"title":"style","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView\/style-swift.property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"style"},{"text":": ","kind":"text"},{"text":"ProgressViewStyleable","kind":"typeIdentifier","preciseIdentifier":"s:5LPHUD21ProgressViewStyleableP"}],"type":"topic","url":"\/documentation\/lphud\/progressview\/style-swift.property","role":"symbol","kind":"symbol"},"doc://org.cocoapods.LPHUD/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/SH"},"doc://org.cocoapods.LPHUD/objc(pl)CALayerDelegate":{"title":"QuartzCore.CALayerDelegate","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)CALayerDelegate"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ProgressView/lineWidth":{"abstract":[{"text":"The width shown for the portion of the progress bar that’s filled.","type":"text"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView\/lineWidth","type":"topic","url":"\/documentation\/lphud\/progressview\/linewidth","title":"lineWidth","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"lineWidth","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"}]},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ProgressView/labelFont":{"abstract":[{"text":"The font of the label text.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView\/labelFont","title":"labelFont","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"labelFont"},{"kind":"text","text":": "},{"text":"UIFont","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIFont"}],"type":"topic","url":"\/documentation\/lphud\/progressview\/labelfont","role":"symbol","kind":"symbol"},"doc://org.cocoapods.LPHUD/documentation/LPHUD":{"abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","url":"\/documentation\/lphud","kind":"symbol","title":"LPHUD"},"doc://org.cocoapods.LPHUD/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/5UIKit23UITraitChangeObservableP","title":"UIKit.UITraitChangeObservable"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ProgressView/observedProgress":{"abstract":[{"type":"text","text":"The Progress object feeding the progress information to the progress indicator."}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView\/observedProgress","title":"observedProgress","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"observedProgress"},{"text":": ","kind":"text"},{"text":"Progress","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSProgress"},{"text":"?","kind":"text"}],"type":"topic","url":"\/documentation\/lphud\/progressview\/observedprogress","role":"symbol","kind":"symbol"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUDExtended":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HUDExtended"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUDExtended","abstract":[{"text":"Protocol describing the ","type":"text"},{"code":"h","type":"codeVoice"},{"text":" extension points for HUD extended types.","type":"text"}],"type":"topic","url":"\/documentation\/lphud\/hudextended","title":"HUDExtended","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HUDExtended"}]},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ProgressView/isHidden":{"role":"symbol","navigatorTitle":[{"text":"hidden","kind":"identifier"}],"abstract":[],"url":"\/documentation\/lphud\/progressview\/ishidden","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isHidden"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView\/isHidden","type":"topic","title":"isHidden"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ProgressView/didMoveToWindow()":{"abstract":[],"title":"didMoveToWindow()","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView\/didMoveToWindow()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didMoveToWindow","kind":"identifier"},{"kind":"text","text":"()"}],"type":"topic","url":"\/documentation\/lphud\/progressview\/didmovetowindow()","navigatorTitle":[{"kind":"identifier","text":"didMoveToWindow"}],"role":"symbol","kind":"symbol"},"doc://org.cocoapods.LPHUD/objc(pl)UICoordinateSpace":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UICoordinateSpace","title":"UIKit.UICoordinateSpace","type":"unresolvable"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ProgressView/progressTintColor":{"title":"progressTintColor","kind":"symbol","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView\/progressTintColor","url":"\/documentation\/lphud\/progressview\/progresstintcolor","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"progressTintColor"},{"kind":"text","text":": "},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?"}],"type":"topic","abstract":[{"type":"text","text":"The color shown for the portion of the progress bar that’s filled."}],"role":"symbol"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ProgressView/initWithFrame:":{"navigatorTitle":[{"text":"initWithFrame:","kind":"identifier"}],"url":"\/documentation\/lphud\/progressview\/initwithframe:","abstract":[],"role":"symbol","type":"topic","fragments":[{"kind":"text","text":"- "},{"text":"initWithFrame:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView\/initWithFrame:","title":"initWithFrame:"},"doc://org.cocoapods.LPHUD/objc(pl)UIActivityItemsConfigurationProviding":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIActivityItemsConfigurationProviding","type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ProgressView/init(styleable:size:populator:)":{"abstract":[{"type":"text","text":"Creates a progress view with the specified style."}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView\/init(styleable:size:populator:)","title":"init(styleable:size:populator:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"styleable","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:5LPHUD21ProgressViewStyleableP","text":"ProgressViewStyleable"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"size"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"populator"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"ProgressView","preciseIdentifier":"c:@M@LPHUD@objc(cs)ProgressView"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")?)"}],"type":"topic","url":"\/documentation\/lphud\/progressview\/init(styleable:size:populator:)","role":"symbol","kind":"symbol"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ProgressView/intrinsicContentSize":{"abstract":[],"title":"intrinsicContentSize","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView\/intrinsicContentSize","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"intrinsicContentSize","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"}],"type":"topic","url":"\/documentation\/lphud\/progressview\/intrinsiccontentsize","navigatorTitle":[{"kind":"identifier","text":"intrinsicContentSize"}],"role":"symbol","kind":"symbol"},"doc://org.cocoapods.LPHUD/objc(pl)UIResponderStandardEditActions":{"title":"UIKit.UIResponderStandardEditActions","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIResponderStandardEditActions"},"doc://org.cocoapods.LPHUD/objc(pl)UIAccessibilityIdentification":{"title":"UIKit.UIAccessibilityIdentification","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIAccessibilityIdentification"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ProgressView/didMoveToSuperview()":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"didMoveToSuperview"},{"text":"()","kind":"text"}],"url":"\/documentation\/lphud\/progressview\/didmovetosuperview()","abstract":[],"title":"didMoveToSuperview()","type":"topic","navigatorTitle":[{"kind":"identifier","text":"didMoveToSuperview"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView\/didMoveToSuperview()"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ProgressView/init(style:size:populator:)":{"abstract":[{"type":"text","text":"Creates a progress view with the specified style."}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView\/init(style:size:populator:)","title":"init(style:size:populator:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"style","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Style","preciseIdentifier":"s:5LPHUD12ProgressViewC5StyleO"},{"kind":"text","text":", "},{"text":"size","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"populator"},{"text":": ((","kind":"text"},{"text":"ProgressView","kind":"typeIdentifier","preciseIdentifier":"c:@M@LPHUD@objc(cs)ProgressView"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"type":"topic","url":"\/documentation\/lphud\/progressview\/init(style:size:populator:)","role":"symbol","kind":"symbol"},"doc://org.cocoapods.LPHUD/SQ":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ProgressView/Style-swift.enum":{"abstract":[{"type":"text","text":"The styles permitted for the progress bar."}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView\/Style-swift.enum","kind":"symbol","title":"ProgressView.Style","url":"\/documentation\/lphud\/progressview\/style-swift.enum","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Style"}],"navigatorTitle":[{"text":"Style","kind":"identifier"}],"role":"symbol","type":"topic"},"doc://org.cocoapods.LPHUD/objc(pl)UIPasteConfigurationSupporting":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIPasteConfigurationSupporting","type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting"},"doc://org.cocoapods.LPHUD/objc(pl)UIAppearance":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIAppearance","type":"unresolvable","title":"UIKit.UIAppearance"},"doc://org.cocoapods.LPHUD/objc(pl)UIFocusItemContainer":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIFocusItemContainer","title":"UIKit.UIFocusItemContainer","type":"unresolvable"},"doc://org.cocoapods.LPHUD/objc(pl)UIFocusItem":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIFocusItem","type":"unresolvable","title":"UIKit.UIFocusItem"},"doc://org.cocoapods.LPHUD/objc(pl)UIFocusEnvironment":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIFocusEnvironment","title":"UIKit.UIFocusEnvironment","type":"unresolvable"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ProgressView":{"role":"symbol","url":"\/documentation\/lphud\/progressview","title":"ProgressView","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ProgressView","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"A view that depicts the progress of a task over time.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"ProgressView","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ProgressView/progress":{"abstract":[{"type":"text","text":"The current progress of the progress view."}],"title":"progress","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView\/progress","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"progress","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"}],"type":"topic","url":"\/documentation\/lphud\/progressview\/progress","role":"symbol","kind":"symbol"},"doc://org.cocoapods.LPHUD/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://org.cocoapods.LPHUD/objc(pl)UITraitEnvironment":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UITraitEnvironment","title":"UIKit.UITraitEnvironment"},"doc://org.cocoapods.LPHUD/objc(pl)UIDynamicItem":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIDynamicItem","title":"UIKit.UIDynamicItem"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ProgressView/alpha":{"abstract":[],"title":"alpha","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView\/alpha","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"alpha","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"type":"topic","url":"\/documentation\/lphud\/progressview\/alpha","navigatorTitle":[{"kind":"identifier","text":"alpha"}],"role":"symbol","kind":"symbol"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ProgressView/bounds":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView\/bounds","title":"bounds","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"bounds","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"}],"type":"topic","url":"\/documentation\/lphud\/progressview\/bounds","navigatorTitle":[{"text":"bounds","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ProgressViewable":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ProgressViewable"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressViewable","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"ProgressViewable","kind":"identifier"}],"title":"ProgressViewable","abstract":[{"type":"text","text":"A view that depicts the progress of a task over time."}],"url":"\/documentation\/lphud\/progressviewable","kind":"symbol"},"doc://org.cocoapods.LPHUD/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://org.cocoapods.LPHUD/objc(pl)NSCoding":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)NSCoding","title":"Foundation.NSCoding"},"doc://org.cocoapods.LPHUD/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/s8SendableP","title":"Swift.Sendable"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ProgressView/isLabelEnabled":{"abstract":[{"type":"text","text":"A Boolean value indicating whether the progress label is in the enabled state."}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView\/isLabelEnabled","title":"isLabelEnabled","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isLabelEnabled","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"type":"topic","url":"\/documentation\/lphud\/progressview\/islabelenabled","role":"symbol","kind":"symbol"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ProgressView/commonInit()":{"title":"commonInit()","kind":"symbol","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView\/commonInit()","url":"\/documentation\/lphud\/progressview\/commoninit()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"commonInit"},{"text":"()","kind":"text"}],"type":"topic","abstract":[{"type":"text","text":"The default implementation of this method does nothing."},{"text":" ","type":"text"},{"text":"Subclasses can override it to perform additional actions after superview initialization.","type":"text"}],"role":"symbol"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ProgressView/trackTintColor":{"abstract":[{"type":"text","text":"The color shown for the portion of the progress bar that isn’t filled."}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView\/trackTintColor","title":"trackTintColor","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"trackTintColor","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"text":"?","kind":"text"}],"type":"topic","url":"\/documentation\/lphud\/progressview\/tracktintcolor","role":"symbol","kind":"symbol"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ProgressView/initWithCoder:":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView\/initWithCoder:","title":"initWithCoder:","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithCoder:"}],"type":"topic","url":"\/documentation\/lphud\/progressview\/initwithcoder:","navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://org.cocoapods.LPHUD/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://org.cocoapods.LPHUD/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"value":"ProgressView","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"value":[{"kind":"identifier","text":"ProgressView"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ProgressView"}]},{"op":"replace","value":[{"identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView\/alpha","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView\/bounds","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView\/intrinsicContentSize","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView\/isHidden"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView\/didMoveToSuperview()","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView\/didMoveToWindow()","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView\/draw(_:)","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView\/initWithCoder:","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView\/initWithFrame:"]}],"path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BaseView"],"kind":"relationships","title":"Inherits From"}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProgressView"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:@M@LPHUD@objc(cs)BaseView","text":"BaseView","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BaseView","kind":"typeIdentifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ProgressView~1draw(_:)\/title","value":"drawRect:"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ProgressView~1draw(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"drawRect:","kind":"identifier"}]},{"value":"BaseView","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1BaseView\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1BaseView\/fragments","value":[{"kind":"identifier","text":"BaseView"}]},{"value":"hidden","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ProgressView~1isHidden\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ProgressView~1isHidden\/fragments","value":[{"text":"hidden","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ProgressView~1didMoveToWindow()\/title","value":"didMoveToWindow"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ProgressView~1didMoveToWindow()\/fragments","value":[{"kind":"text","text":"- "},{"text":"didMoveToWindow","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ProgressView~1intrinsicContentSize\/title","value":"intrinsicContentSize"},{"value":[{"text":"intrinsicContentSize","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ProgressView~1intrinsicContentSize\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ProgressView~1didMoveToSuperview()\/title","value":"didMoveToSuperview","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"didMoveToSuperview","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ProgressView~1didMoveToSuperview()\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ProgressView\/title","value":"ProgressView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ProgressView\/fragments","value":[{"text":"ProgressView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ProgressView~1alpha\/title","op":"replace","value":"alpha"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ProgressView~1alpha\/fragments","value":[{"text":"alpha","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ProgressView~1bounds\/title","value":"bounds","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ProgressView~1bounds\/fragments","value":[{"kind":"identifier","text":"bounds"}]}]}]}