{"sections":[],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/RoundedButton\/init(coder:)","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/RoundedButton\/init(frame:)"]},{"identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/RoundedButton\/borderWidth","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/RoundedButton\/intrinsicContentSize","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/RoundedButton\/isHighlighted","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/RoundedButton\/roundedCorners"],"title":"Instance Properties"},{"identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/RoundedButton\/layoutSubviews()","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/RoundedButton\/setTitleColor(_:for:)"],"title":"Instance Methods"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RoundedButton"}]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.LPHUD\/objc(cs)UIButton"],"title":"Inherits From","type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.LPHUD\/objc(pl)NSCoding","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUDExtended","doc:\/\/org.cocoapods.LPHUD\/objc(pl)NSObject","doc:\/\/org.cocoapods.LPHUD\/objc(pl)CALayerDelegate","doc:\/\/org.cocoapods.LPHUD\/s7CVarArgP","doc:\/\/org.cocoapods.LPHUD\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.LPHUD\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.LPHUD\/SQ","doc:\/\/org.cocoapods.LPHUD\/SH","doc:\/\/org.cocoapods.LPHUD\/s8SendableP","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIAccessibilityContentSizeCategoryImageAdjusting","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIAccessibilityIdentification","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIAppearance","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIContextMenuInteractionDelegate","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UICoordinateSpace","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIDynamicItem","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIFocusItem","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIFocusItemContainer","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UILargeContentViewerItem","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UISpringLoadedInteractionSupporting","doc:\/\/org.cocoapods.LPHUD\/5UIKit23UITraitChangeObservableP","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIUserActivityRestoring"],"type":"conformsTo"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/RoundedButton"},"metadata":{"navigatorTitle":[{"text":"RoundedButton","kind":"identifier"}],"title":"RoundedButton","externalID":"c:@M@LPHUD@objc(cs)RoundedButton","roleHeading":"Class","modules":[{"name":"LPHUD"}],"symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RoundedButton"}],"role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/lphud\/roundedbutton"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/lphud\/roundedbutton"]}],"references":{"doc://org.cocoapods.LPHUD/documentation/LPHUD/RoundedButton/init(coder:)":{"url":"\/documentation\/lphud\/roundedbutton\/init(coder:)","abstract":[],"kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"coder","kind":"externalParam"},{"kind":"text","text":": "},{"text":"NSCoder","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCoder"},{"text":")","kind":"text"}],"title":"init(coder:)","type":"topic","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/RoundedButton\/init(coder:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}]},"doc://org.cocoapods.LPHUD/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIPasteConfigurationSupporting","title":"UIKit.UIPasteConfigurationSupporting"},"doc://org.cocoapods.LPHUD/objc(pl)UIAppearanceContainer":{"title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIAppearanceContainer","type":"unresolvable"},"doc://org.cocoapods.LPHUD/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.LPHUD\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://org.cocoapods.LPHUD/objc(pl)UIUserActivityRestoring":{"title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIUserActivityRestoring","type":"unresolvable"},"doc://org.cocoapods.LPHUD/objc(cs)UIButton":{"title":"UIButton","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(cs)UIButton","type":"unresolvable"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/RoundedButton/borderWidth":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"borderWidth"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"role":"symbol","abstract":[{"text":"Button border width. ","type":"text"},{"code":"Default to 1","type":"codeVoice"},{"text":".","type":"text"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/RoundedButton\/borderWidth","url":"\/documentation\/lphud\/roundedbutton\/borderwidth","title":"borderWidth","type":"topic"},"doc://org.cocoapods.LPHUD/objc(pl)UICoordinateSpace":{"title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UICoordinateSpace","type":"unresolvable"},"doc://org.cocoapods.LPHUD/objc(pl)UIActivityItemsConfigurationProviding":{"title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIActivityItemsConfigurationProviding","type":"unresolvable"},"doc://org.cocoapods.LPHUD/s8SendableP":{"title":"Swift.Sendable","identifier":"doc:\/\/org.cocoapods.LPHUD\/s8SendableP","type":"unresolvable"},"doc://org.cocoapods.LPHUD/objc(pl)UIAccessibilityContentSizeCategoryImageAdjusting":{"title":"UIKit.UIAccessibilityContentSizeCategoryImageAdjusting","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIAccessibilityContentSizeCategoryImageAdjusting","type":"unresolvable"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/RoundedButton/setTitleColor(_:for:)":{"navigatorTitle":[{"text":"setTitleColor:forState:","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/RoundedButton\/setTitleColor(_:for:)","abstract":[],"type":"topic","url":"\/documentation\/lphud\/roundedbutton\/settitlecolor(_:for:)","title":"setTitleColor(_:for:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setTitleColor","kind":"identifier"},{"kind":"text","text":"("},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIControl","text":"UIControl"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@UIControlState","text":"State","kind":"typeIdentifier"},{"kind":"text","text":")"}],"kind":"symbol"},"doc://org.cocoapods.LPHUD/objc(pl)UILargeContentViewerItem":{"title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UILargeContentViewerItem","type":"unresolvable"},"doc://org.cocoapods.LPHUD/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.LPHUD\/s7CVarArgP","type":"unresolvable"},"doc://org.cocoapods.LPHUD/5UIKit23UITraitChangeObservableP":{"title":"UIKit.UITraitChangeObservable","identifier":"doc:\/\/org.cocoapods.LPHUD\/5UIKit23UITraitChangeObservableP","type":"unresolvable"},"doc://org.cocoapods.LPHUD/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)NSObject","type":"unresolvable"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/RoundedButton/roundedCorners":{"url":"\/documentation\/lphud\/roundedbutton\/roundedcorners","title":"roundedCorners","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/RoundedButton\/roundedCorners","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"roundedCorners","kind":"identifier"},{"kind":"text","text":": "},{"text":"BackgroundView","preciseIdentifier":"c:@M@LPHUD@objc(cs)BackgroundView","kind":"typeIdentifier"},{"kind":"text","text":"."},{"preciseIdentifier":"s:5LPHUD14BackgroundViewC14RoundedCornersO","kind":"typeIdentifier","text":"RoundedCorners"}],"role":"symbol","type":"topic","abstract":[{"text":"The rounded corner mode of the button. ","type":"text"},{"type":"codeVoice","code":"Default to .fully"},{"type":"text","text":"."}]},"doc://org.cocoapods.LPHUD/objc(pl)UIDynamicItem":{"title":"UIKit.UIDynamicItem","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIDynamicItem"},"doc://org.cocoapods.LPHUD/objc(pl)UIAppearance":{"title":"UIKit.UIAppearance","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIAppearance"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/RoundedButton/isHighlighted":{"url":"\/documentation\/lphud\/roundedbutton\/ishighlighted","title":"isHighlighted","type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/RoundedButton\/isHighlighted","navigatorTitle":[{"text":"highlighted","kind":"identifier"}],"abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isHighlighted"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"role":"symbol"},"doc://org.cocoapods.LPHUD/objc(pl)UIFocusEnvironment":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIFocusEnvironment","title":"UIKit.UIFocusEnvironment","type":"unresolvable"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/RoundedButton/intrinsicContentSize":{"navigatorTitle":[{"text":"intrinsicContentSize","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/RoundedButton\/intrinsicContentSize","type":"topic","title":"intrinsicContentSize","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"intrinsicContentSize","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"}],"url":"\/documentation\/lphud\/roundedbutton\/intrinsiccontentsize","abstract":[],"role":"symbol"},"doc://org.cocoapods.LPHUD/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIAccessibilityIdentification"},"doc://org.cocoapods.LPHUD/objc(pl)UISpringLoadedInteractionSupporting":{"type":"unresolvable","title":"UIKit.UISpringLoadedInteractionSupporting","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UISpringLoadedInteractionSupporting"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/RoundedButton":{"navigatorTitle":[{"kind":"identifier","text":"RoundedButton"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/RoundedButton","abstract":[],"type":"topic","url":"\/documentation\/lphud\/roundedbutton","title":"RoundedButton","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"RoundedButton","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.LPHUD/objc(pl)CALayerDelegate":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)CALayerDelegate","title":"QuartzCore.CALayerDelegate","type":"unresolvable"},"doc://org.cocoapods.LPHUD/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://org.cocoapods.LPHUD/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIFocusItem"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/RoundedButton/layoutSubviews()":{"url":"\/documentation\/lphud\/roundedbutton\/layoutsubviews()","type":"topic","title":"layoutSubviews()","kind":"symbol","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/RoundedButton\/layoutSubviews()","navigatorTitle":[{"kind":"identifier","text":"layoutSubviews"}],"abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutSubviews"},{"text":"()","kind":"text"}],"role":"symbol"},"doc://org.cocoapods.LPHUD/objc(pl)UIContextMenuInteractionDelegate":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIContextMenuInteractionDelegate","title":"UIKit.UIContextMenuInteractionDelegate"},"doc://org.cocoapods.LPHUD/objc(pl)NSCoding":{"title":"Foundation.NSCoding","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)NSCoding","type":"unresolvable"},"doc://org.cocoapods.LPHUD/objc(pl)UIResponderStandardEditActions":{"title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIResponderStandardEditActions","type":"unresolvable"},"doc://org.cocoapods.LPHUD/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.LPHUD\/SQ","type":"unresolvable"},"doc://org.cocoapods.LPHUD/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.LPHUD\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://org.cocoapods.LPHUD/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.LPHUD\/SH","type":"unresolvable"},"doc://org.cocoapods.LPHUD/objc(pl)UITraitEnvironment":{"title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UITraitEnvironment","type":"unresolvable"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUDExtended":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HUDExtended"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUDExtended","abstract":[{"text":"Protocol describing the ","type":"text"},{"code":"h","type":"codeVoice"},{"text":" extension points for HUD extended types.","type":"text"}],"type":"topic","url":"\/documentation\/lphud\/hudextended","title":"HUDExtended","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HUDExtended"}]},"doc://org.cocoapods.LPHUD/documentation/LPHUD":{"abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","url":"\/documentation\/lphud","kind":"symbol","title":"LPHUD"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/RoundedButton/init(frame:)":{"url":"\/documentation\/lphud\/roundedbutton\/init(frame:)","type":"topic","title":"init(frame:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/RoundedButton\/init(frame:)","navigatorTitle":[{"kind":"identifier","text":"initWithFrame:"}],"abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier","text":"CGRect"},{"text":")","kind":"text"}],"role":"symbol"},"doc://org.cocoapods.LPHUD/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIFocusItemContainer"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"RoundedButton","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"RoundedButton"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"RoundedButton","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/RoundedButton\/intrinsicContentSize","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/RoundedButton\/isHighlighted"],"title":"Instance Properties"},{"identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/RoundedButton\/init(coder:)","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/RoundedButton\/init(frame:)","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/RoundedButton\/layoutSubviews()","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/RoundedButton\/setTitleColor(_:for:)"],"title":"Instance Methods"}]},{"value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.LPHUD\/objc(cs)UIButton"],"type":"inheritsFrom"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RoundedButton","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1RoundedButton~1init(coder:)\/title","value":"initWithCoder:","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithCoder:"}],"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1RoundedButton~1init(coder:)\/fragments"},{"value":"setTitleColor:forState:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1RoundedButton~1setTitleColor(_:for:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1RoundedButton~1setTitleColor(_:for:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setTitleColor:forState:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1RoundedButton~1isHighlighted\/title","value":"highlighted","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1RoundedButton~1isHighlighted\/fragments","value":[{"text":"highlighted","kind":"identifier"}]},{"value":"intrinsicContentSize","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1RoundedButton~1intrinsicContentSize\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1RoundedButton~1intrinsicContentSize\/fragments","value":[{"text":"intrinsicContentSize","kind":"identifier"}]},{"value":"RoundedButton","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1RoundedButton\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1RoundedButton\/fragments","value":[{"kind":"identifier","text":"RoundedButton"}],"op":"replace"},{"value":"layoutSubviews","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1RoundedButton~1layoutSubviews()\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1RoundedButton~1layoutSubviews()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"layoutSubviews","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1RoundedButton~1init(frame:)\/title","value":"initWithFrame:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithFrame:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1RoundedButton~1init(frame:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}