{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didMoveToSuperview","kind":"identifier"},{"text":"()","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/lphud\/progressview\/didmovetosuperview()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/lphud\/progressview\/didmovetosuperview()"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView"]]},"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"didMoveToSuperview","kind":"identifier"},{"kind":"text","text":"()"}],"modules":[{"name":"LPHUD"}],"roleHeading":"Instance Method","symbolKind":"method","title":"didMoveToSuperview()","navigatorTitle":[{"kind":"identifier","text":"didMoveToSuperview"}],"role":"symbol","externalID":"c:@M@LPHUD@objc(cs)ProgressView(im)didMoveToSuperview"},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView\/didMoveToSuperview()","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.LPHUD/documentation/LPHUD":{"abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","url":"\/documentation\/lphud","kind":"symbol","title":"LPHUD"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ProgressView/didMoveToSuperview()":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"didMoveToSuperview"},{"text":"()","kind":"text"}],"url":"\/documentation\/lphud\/progressview\/didmovetosuperview()","abstract":[],"title":"didMoveToSuperview()","type":"topic","navigatorTitle":[{"kind":"identifier","text":"didMoveToSuperview"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView\/didMoveToSuperview()"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ProgressView":{"role":"symbol","url":"\/documentation\/lphud\/progressview","title":"ProgressView","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ProgressView","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"A view that depicts the progress of a task over time.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"ProgressView","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"didMoveToSuperview"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"didMoveToSuperview","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"didMoveToSuperview","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ProgressView~1didMoveToSuperview()\/title","op":"replace","value":"didMoveToSuperview"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ProgressView~1didMoveToSuperview()\/fragments","value":[{"kind":"text","text":"- "},{"text":"didMoveToSuperview","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ProgressView\/title","value":"ProgressView"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ProgressView\/fragments","value":[{"kind":"identifier","text":"ProgressView"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}