{"metadata":{"title":"init(frame:)","navigatorTitle":[{"text":"initWithFrame:","kind":"identifier"}],"roleHeading":"Initializer","modules":[{"name":"LPHUD"}],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"frame","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier","text":"CGRect"},{"text":")","kind":"text"}],"externalID":"c:@M@LPHUD@objc(cs)BackgroundView(im)initWithFrame:","role":"symbol","symbolKind":"init"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BackgroundView"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/lphud\/backgroundview\/init(frame:)"]},{"paths":["\/documentation\/lphud\/backgroundview\/init(frame:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BackgroundView\/init(frame:)"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"override","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.LPHUD/documentation/LPHUD/BackgroundView/init(frame:)":{"navigatorTitle":[{"text":"initWithFrame:","kind":"identifier"}],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"frame","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"kind":"text","text":")"}],"title":"init(frame:)","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BackgroundView\/init(frame:)","abstract":[],"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/lphud\/backgroundview\/init(frame:)"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/BackgroundView":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BackgroundView","navigatorTitle":[{"kind":"identifier","text":"BackgroundView"}],"kind":"symbol","type":"topic","url":"\/documentation\/lphud\/backgroundview","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"BackgroundView","kind":"identifier"}],"title":"BackgroundView"},"doc://org.cocoapods.LPHUD/documentation/LPHUD":{"type":"topic","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","title":"LPHUD","url":"\/documentation\/lphud","abstract":[],"role":"collection","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"initWithFrame:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithFrame:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"text":"initWithFrame:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"kind":"text","text":") "},{"kind":"internalParam","text":"frame"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace"},{"value":"initWithFrame:","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1BackgroundView~1init(frame:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1BackgroundView~1init(frame:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFrame:"}]},{"op":"replace","value":"BackgroundView","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1BackgroundView\/title"},{"value":[{"kind":"identifier","text":"BackgroundView"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1BackgroundView\/fragments"}]}]}