{"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ProgressView\/init(style:size:)","doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ProgressView\/init(styleable:size:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ProgressView\/alpha","doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ProgressView\/bounds","doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ProgressView\/intrinsicContentSize","doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ProgressView\/isHidden","doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ProgressView\/isLabelEnabled","doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ProgressView\/labelFont","doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ProgressView\/lineWidth","doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ProgressView\/observedProgress","doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ProgressView\/progress","doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ProgressView\/progressTintColor","doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ProgressView\/style-swift.property","doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ProgressView\/trackTintColor"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ProgressView\/commonInit()","doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ProgressView\/didMoveToSuperview()","doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ProgressView\/didMoveToWindow()","doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ProgressView\/draw(_:)","doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ProgressView\/updateScreenInDisplayLink()"]},{"identifiers":["doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ProgressView\/Style-swift.enum"],"title":"Enumerations"}],"metadata":{"navigatorTitle":[{"text":"ProgressView","kind":"identifier"}],"roleHeading":"Class","symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ProgressView","kind":"identifier"}],"externalID":"c:@M@FlyHUD@objc(cs)ProgressView","role":"symbol","modules":[{"name":"FlyHUD"}],"title":"ProgressView"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ProgressView"}],"languages":["swift"]}]},{"kind":"content","content":[{"text":"Overview","level":2,"type":"heading","anchor":"overview"},{"type":"paragraph","inlineContent":[{"text":"The ProgressView class provides properties for managing the style of the progress","type":"text"},{"type":"text","text":" "},{"type":"text","text":"bar and for getting and setting values that are pinned to the progress of a task."}]},{"name":"Note","content":[{"inlineContent":[{"text":"For an indeterminate progress indicator — or a “spinner” — use an instance of the ActivityIndicatorView class.","type":"text"}],"type":"paragraph"}],"type":"aside","style":"note"}]}],"abstract":[{"text":"A view that depicts the progress of a task over time.","type":"text"}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/BaseView"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/DisplayLinkDelegate","doc:\/\/org.cocoapods.FlyHUD\/objc(pl)NSCoding","doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/HUDExtended","doc:\/\/org.cocoapods.FlyHUD\/objc(pl)NSObject","doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ProgressViewable","doc:\/\/org.cocoapods.FlyHUD\/objc(pl)CALayerDelegate","doc:\/\/org.cocoapods.FlyHUD\/s7CVarArgP","doc:\/\/org.cocoapods.FlyHUD\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.FlyHUD\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.FlyHUD\/SQ","doc:\/\/org.cocoapods.FlyHUD\/SH","doc:\/\/org.cocoapods.FlyHUD\/s8SendableP","doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIAccessibilityIdentification","doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIAppearance","doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UICoordinateSpace","doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIDynamicItem","doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIFocusItem","doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIFocusItemContainer","doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UILargeContentViewerItem","doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.FlyHUD\/5UIKit23UITraitChangeObservableP","doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/flyhud\/progressview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/flyhud\/progressview"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ProgressView","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/ProgressView/labelFont":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"labelFont"},{"text":": ","kind":"text"},{"text":"UIFont","preciseIdentifier":"c:objc(cs)UIFont","kind":"typeIdentifier"}],"identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ProgressView\/labelFont","type":"topic","abstract":[{"type":"text","text":"The font of the label text."}],"url":"\/documentation\/flyhud\/progressview\/labelfont","role":"symbol","kind":"symbol","title":"labelFont"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/ProgressView/Style-swift.enum":{"role":"symbol","navigatorTitle":[{"text":"Style","kind":"identifier"}],"title":"ProgressView.Style","identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ProgressView\/Style-swift.enum","abstract":[{"type":"text","text":"The styles permitted for the progress bar."}],"url":"\/documentation\/flyhud\/progressview\/style-swift.enum","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"Style","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/ProgressView/alpha":{"identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ProgressView\/alpha","url":"\/documentation\/flyhud\/progressview\/alpha","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"alpha"}],"title":"alpha","abstract":[{"type":"text","text":"The view’s alpha value."}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"alpha","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"kind":"symbol"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/ProgressView/isHidden":{"type":"topic","abstract":[{"type":"text","text":"A Boolean value that determines whether the view is hidden."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isHidden","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ProgressView\/isHidden","role":"symbol","url":"\/documentation\/flyhud\/progressview\/ishidden","title":"isHidden","kind":"symbol","navigatorTitle":[{"text":"hidden","kind":"identifier"}]},"doc://org.cocoapods.FlyHUD/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding"},"doc://org.cocoapods.FlyHUD/objc(pl)UIUserActivityRestoring":{"identifier":"doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring","type":"unresolvable"},"doc://org.cocoapods.FlyHUD/objc(pl)UITraitEnvironment":{"identifier":"doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UITraitEnvironment","title":"UIKit.UITraitEnvironment","type":"unresolvable"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD":{"type":"topic","identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD","kind":"symbol","abstract":[],"url":"\/documentation\/flyhud","role":"collection","title":"FlyHUD"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/ProgressView/intrinsicContentSize":{"type":"topic","url":"\/documentation\/flyhud\/progressview\/intrinsiccontentsize","abstract":[{"type":"text","text":"The natural size for the receiving view, considering only properties of the view itself."}],"navigatorTitle":[{"text":"intrinsicContentSize","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ProgressView\/intrinsicContentSize","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"intrinsicContentSize"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"role":"symbol","title":"intrinsicContentSize"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/ProgressView/lineWidth":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"lineWidth"},{"kind":"text","text":": "},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"}],"identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ProgressView\/lineWidth","type":"topic","abstract":[{"type":"text","text":"The width shown for the portion of the progress bar that’s filled."}],"url":"\/documentation\/flyhud\/progressview\/linewidth","role":"symbol","kind":"symbol","title":"lineWidth"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/ProgressView/initWithFrame:":{"navigatorTitle":[{"kind":"identifier","text":"initWithFrame:"}],"fragments":[{"kind":"text","text":"- "},{"text":"initWithFrame:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ProgressView\/initWithFrame:","type":"topic","abstract":[],"url":"\/documentation\/flyhud\/progressview\/initwithframe:","role":"symbol","kind":"symbol","title":"initWithFrame:"},"doc://org.cocoapods.FlyHUD/5UIKit23UITraitChangeObservableP":{"title":"UIKit.UITraitChangeObservable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.FlyHUD\/5UIKit23UITraitChangeObservableP"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/ProgressView/updateScreenInDisplayLink()":{"identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ProgressView\/updateScreenInDisplayLink()","abstract":[{"type":"text","text":"Refreshing the progress only every frame draw."}],"type":"topic","kind":"symbol","role":"symbol","title":"updateScreenInDisplayLink()","url":"\/documentation\/flyhud\/progressview\/updatescreenindisplaylink()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"updateScreenInDisplayLink","kind":"identifier"},{"kind":"text","text":"()"}]},"doc://org.cocoapods.FlyHUD/objc(pl)UIResponderStandardEditActions":{"title":"UIKit.UIResponderStandardEditActions","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIResponderStandardEditActions"},"doc://org.cocoapods.FlyHUD/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.FlyHUD\/SQ"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/ProgressView/isLabelEnabled":{"kind":"symbol","title":"isLabelEnabled","url":"\/documentation\/flyhud\/progressview\/islabelenabled","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isLabelEnabled","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"text":"A Boolean value indicating whether the progress label is in the enabled state.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ProgressView\/isLabelEnabled"},"doc://org.cocoapods.FlyHUD/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.FlyHUD\/SH"},"doc://org.cocoapods.FlyHUD/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.FlyHUD\/objc(pl)NSObject"},"doc://org.cocoapods.FlyHUD/objc(pl)CALayerDelegate":{"title":"QuartzCore.CALayerDelegate","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.FlyHUD\/objc(pl)CALayerDelegate"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/ProgressView/progressTintColor":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"progressTintColor"},{"text":": ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ProgressView\/progressTintColor","type":"topic","abstract":[{"text":"The color shown for the portion of the progress bar that’s filled.","type":"text"}],"url":"\/documentation\/flyhud\/progressview\/progresstintcolor","role":"symbol","kind":"symbol","title":"progressTintColor"},"doc://org.cocoapods.FlyHUD/objc(pl)UIDynamicItem":{"title":"UIKit.UIDynamicItem","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIDynamicItem"},"doc://org.cocoapods.FlyHUD/objc(pl)UIFocusItem":{"title":"UIKit.UIFocusItem","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIFocusItem"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/ProgressView/bounds":{"navigatorTitle":[{"kind":"identifier","text":"bounds"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"bounds","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"}],"identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ProgressView\/bounds","type":"topic","abstract":[{"text":"The bounds rectangle, which describes the view’s location and size in its own coordinate system.","type":"text"}],"url":"\/documentation\/flyhud\/progressview\/bounds","role":"symbol","kind":"symbol","title":"bounds"},"doc://org.cocoapods.FlyHUD/objc(pl)UIAccessibilityIdentification":{"title":"UIKit.UIAccessibilityIdentification","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIAccessibilityIdentification"},"doc://org.cocoapods.FlyHUD/objc(pl)UICoordinateSpace":{"title":"UIKit.UICoordinateSpace","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UICoordinateSpace"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/ProgressView/draw(_:)":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"drawRect:"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"draw"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier","text":"CGRect"},{"kind":"text","text":")"}],"identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ProgressView\/draw(_:)","abstract":[{"type":"text","text":"Draws the receiver’s image within the passed-in rectangle."}],"title":"draw(_:)","url":"\/documentation\/flyhud\/progressview\/draw(_:)"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/ProgressView/init(styleable:size:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"styleable","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:6FlyHUD21ProgressViewStyleableP","text":"ProgressViewStyleable"},{"kind":"text","text":", "},{"text":"size","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"},{"kind":"text","text":")"}],"identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ProgressView\/init(styleable:size:)","type":"topic","abstract":[{"text":"Creates a progress view with the specified style.","type":"text"}],"url":"\/documentation\/flyhud\/progressview\/init(styleable:size:)","role":"symbol","kind":"symbol","title":"init(styleable:size:)"},"doc://org.cocoapods.FlyHUD/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.FlyHUD\/s7CVarArgP"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/ProgressView/progress":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"progress","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sf","kind":"typeIdentifier","text":"Float"}],"identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ProgressView\/progress","type":"topic","abstract":[{"text":"The current progress of the progress view.","type":"text"}],"url":"\/documentation\/flyhud\/progressview\/progress","role":"symbol","kind":"symbol","title":"progress"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/ProgressView/didMoveToSuperview()":{"navigatorTitle":[{"kind":"identifier","text":"didMoveToSuperview"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"didMoveToSuperview","kind":"identifier"},{"kind":"text","text":"()"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ProgressView\/didMoveToSuperview()","abstract":[{"type":"text","text":"Tells the view that its superview changed."}],"url":"\/documentation\/flyhud\/progressview\/didmovetosuperview()","role":"symbol","kind":"symbol","title":"didMoveToSuperview()"},"doc://org.cocoapods.FlyHUD/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.FlyHUD\/s23CustomStringConvertibleP"},"doc://org.cocoapods.FlyHUD/objc(pl)UIPasteConfigurationSupporting":{"title":"UIKit.UIPasteConfigurationSupporting","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIPasteConfigurationSupporting"},"doc://org.cocoapods.FlyHUD/objc(pl)UILargeContentViewerItem":{"title":"UIKit.UILargeContentViewerItem","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UILargeContentViewerItem"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/ProgressView/commonInit()":{"identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ProgressView\/commonInit()","kind":"symbol","abstract":[{"text":"Common initialization method.","type":"text"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"commonInit","kind":"identifier"},{"kind":"text","text":"()"}],"url":"\/documentation\/flyhud\/progressview\/commoninit()","title":"commonInit()","role":"symbol"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/ProgressView/observedProgress":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"observedProgress","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Progress","preciseIdentifier":"c:objc(cs)NSProgress"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ProgressView\/observedProgress","type":"topic","abstract":[{"text":"The Progress object feeding the progress information to the progress indicator.","type":"text"}],"url":"\/documentation\/flyhud\/progressview\/observedprogress","role":"symbol","kind":"symbol","title":"observedProgress"},"doc://org.cocoapods.FlyHUD/objc(pl)UIPopoverPresentationControllerSourceItem":{"title":"UIKit.UIPopoverPresentationControllerSourceItem","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/ProgressView":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"ProgressView"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ProgressView"}],"identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ProgressView","abstract":[{"type":"text","text":"A view that depicts the progress of a task over time."}],"title":"ProgressView","url":"\/documentation\/flyhud\/progressview"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/ProgressViewable":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProgressViewable"}],"abstract":[{"text":"A view that depicts the progress of a task over time.","type":"text"}],"url":"\/documentation\/flyhud\/progressviewable","identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ProgressViewable","type":"topic","title":"ProgressViewable","navigatorTitle":[{"text":"ProgressViewable","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://org.cocoapods.FlyHUD/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.FlyHUD\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.FlyHUD/objc(pl)UIFocusItemContainer":{"title":"UIKit.UIFocusItemContainer","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIFocusItemContainer"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/ProgressView/initWithCoder:":{"navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithCoder:"}],"identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ProgressView\/initWithCoder:","type":"topic","abstract":[],"url":"\/documentation\/flyhud\/progressview\/initwithcoder:","role":"symbol","kind":"symbol","title":"initWithCoder:"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/ProgressView/style-swift.property":{"kind":"symbol","title":"style","url":"\/documentation\/flyhud\/progressview\/style-swift.property","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"style"},{"kind":"text","text":": "},{"preciseIdentifier":"s:6FlyHUD21ProgressViewStyleableP","text":"ProgressViewStyleable","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"The current graphical style of the progress view. The value of this property is a constant that specifies"},{"type":"text","text":" "},{"text":"the style of the progress view. ","type":"text"},{"code":"Default to Style.buttBar","type":"codeVoice"},{"type":"text","text":"."}],"identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ProgressView\/style-swift.property"},"doc://org.cocoapods.FlyHUD/objc(pl)NSCoding":{"title":"Foundation.NSCoding","identifier":"doc:\/\/org.cocoapods.FlyHUD\/objc(pl)NSCoding","type":"unresolvable"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/ProgressView/trackTintColor":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackTintColor"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ProgressView\/trackTintColor","type":"topic","abstract":[{"text":"The color shown for the portion of the progress bar that isn’t filled.","type":"text"}],"url":"\/documentation\/flyhud\/progressview\/tracktintcolor","role":"symbol","kind":"symbol","title":"trackTintColor"},"doc://org.cocoapods.FlyHUD/objc(pl)UIFocusEnvironment":{"title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIFocusEnvironment","type":"unresolvable"},"doc://org.cocoapods.FlyHUD/objc(pl)UIAppearance":{"title":"UIKit.UIAppearance","identifier":"doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIAppearance","type":"unresolvable"},"doc://org.cocoapods.FlyHUD/objc(pl)UIAppearanceContainer":{"title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIAppearanceContainer","type":"unresolvable"},"doc://org.cocoapods.FlyHUD/s8SendableP":{"title":"Swift.Sendable","identifier":"doc:\/\/org.cocoapods.FlyHUD\/s8SendableP","type":"unresolvable"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/HUDExtended":{"identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/HUDExtended","abstract":[{"type":"text","text":"Protocol describing the "},{"type":"codeVoice","code":"h"},{"text":" extension points for HUD extended types.","type":"text"}],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HUDExtended"}],"url":"\/documentation\/flyhud\/hudextended","navigatorTitle":[{"kind":"identifier","text":"HUDExtended"}],"title":"HUDExtended"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/ProgressView/didMoveToWindow()":{"navigatorTitle":[{"kind":"identifier","text":"didMoveToWindow"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"didMoveToWindow","kind":"identifier"},{"kind":"text","text":"()"}],"identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ProgressView\/didMoveToWindow()","type":"topic","abstract":[{"text":"Tells the view that its window object changed.","type":"text"}],"url":"\/documentation\/flyhud\/progressview\/didmovetowindow()","role":"symbol","kind":"symbol","title":"didMoveToWindow()"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/BaseView":{"abstract":[{"type":"text","text":"A base view only provides one "},{"code":"commonInit","type":"codeVoice"},{"type":"text","text":" method."}],"identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/BaseView","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BaseView"}],"kind":"symbol","url":"\/documentation\/flyhud\/baseview","title":"BaseView","navigatorTitle":[{"text":"BaseView","kind":"identifier"}]},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/ProgressView/init(style:size:)":{"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"style","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Style","preciseIdentifier":"s:6FlyHUD12ProgressViewC5StyleO"},{"text":", ","kind":"text"},{"text":"size","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"},{"kind":"text","text":")"}],"identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ProgressView\/init(style:size:)","type":"topic","abstract":[{"text":"Creates a progress view with the specified style.","type":"text"}],"url":"\/documentation\/flyhud\/progressview\/init(style:size:)","role":"symbol","kind":"symbol","title":"init(style:size:)"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/DisplayLinkDelegate":{"role":"symbol","title":"DisplayLinkDelegate","navigatorTitle":[{"kind":"identifier","text":"DisplayLinkDelegate"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/DisplayLinkDelegate","url":"\/documentation\/flyhud\/displaylinkdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DisplayLinkDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"The methods adopted by the object that allows your app to synchronize its drawing to the refresh rate of the display."}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"ProgressView"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"value":[{"text":"ProgressView","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ProgressView"}]},{"op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ProgressView\/alpha","doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ProgressView\/bounds","doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ProgressView\/intrinsicContentSize","doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ProgressView\/isHidden"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ProgressView\/didMoveToSuperview()","doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ProgressView\/didMoveToWindow()","doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ProgressView\/draw(_:)","doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ProgressView\/initWithCoder:","doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ProgressView\/initWithFrame:"]}],"path":"\/topicSections"},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/BaseView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"op":"replace"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"ProgressView","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"BaseView","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/BaseView","preciseIdentifier":"c:@M@FlyHUD@objc(cs)BaseView"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1ProgressView~1alpha\/title","value":"alpha","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1ProgressView~1alpha\/fragments","value":[{"kind":"identifier","text":"alpha"}]},{"value":"hidden","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1ProgressView~1isHidden\/title"},{"value":[{"kind":"identifier","text":"hidden"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1ProgressView~1isHidden\/fragments"},{"op":"replace","value":"intrinsicContentSize","path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1ProgressView~1intrinsicContentSize\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1ProgressView~1intrinsicContentSize\/fragments","value":[{"text":"intrinsicContentSize","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1ProgressView~1bounds\/title","value":"bounds"},{"op":"replace","value":[{"kind":"identifier","text":"bounds"}],"path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1ProgressView~1bounds\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1ProgressView~1draw(_:)\/title","value":"drawRect:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1ProgressView~1draw(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"drawRect:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1ProgressView~1didMoveToSuperview()\/title","value":"didMoveToSuperview","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"didMoveToSuperview","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1ProgressView~1didMoveToSuperview()\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1ProgressView\/title","value":"ProgressView","op":"replace"},{"op":"replace","value":[{"text":"ProgressView","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1ProgressView\/fragments"},{"op":"replace","value":"didMoveToWindow","path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1ProgressView~1didMoveToWindow()\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didMoveToWindow"}],"path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1ProgressView~1didMoveToWindow()\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1BaseView\/title","value":"BaseView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1BaseView\/fragments","value":[{"text":"BaseView","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}