{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/lphud\/barprogressview\/init()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/lphud\/barprogressview\/init()"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"()","kind":"text"}]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BarProgressView"]]},"kind":"symbol","metadata":{"title":"init()","fragments":[{"kind":"identifier","text":"init"},{"text":"()","kind":"text"}],"symbolKind":"init","role":"symbol","modules":[{"name":"LPHUD"}],"navigatorTitle":[{"kind":"identifier","text":"init"}],"roleHeading":"Initializer","externalID":"c:@M@LPHUD@objc(cs)BarProgressView(im)init"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BarProgressView\/init()"},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://org.cocoapods.LPHUD/documentation/LPHUD/BarProgressView":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BarProgressView","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BarProgressView","navigatorTitle":[{"kind":"identifier","text":"BarProgressView"}],"url":"\/documentation\/lphud\/barprogressview","role":"symbol","abstract":[{"type":"text","text":"A flat bar progress view."}],"title":"BarProgressView","type":"topic"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/BarProgressView/init()":{"type":"topic","title":"init()","url":"\/documentation\/lphud\/barprogressview\/init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BarProgressView\/init()"},"doc://org.cocoapods.LPHUD/documentation/LPHUD":{"type":"topic","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","title":"LPHUD","url":"\/documentation\/lphud","abstract":[],"role":"collection","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"init","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1BarProgressView\/title","value":"BarProgressView","op":"replace"},{"value":[{"kind":"identifier","text":"BarProgressView"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1BarProgressView\/fragments"},{"value":"init","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1BarProgressView~1init()\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1BarProgressView~1init()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}