{"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/lphud\/hud\/hittest(_:with:)"]},{"paths":["\/documentation\/lphud\/hud\/hittest(_:with:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"override","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hitTest"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"point"},{"text":": ","kind":"text"},{"text":"CGPoint","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"with"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"event"},{"text":": ","kind":"text"},{"text":"UIEvent","preciseIdentifier":"c:objc(cs)UIEvent","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"point","content":[{"inlineContent":[{"text":"A point in the view’s local coordinate system.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"The event that warrants a call to this method. If you’re calling this method from outside your event-handling code, you can specify nil.","type":"text"}],"type":"paragraph"}],"name":"event"}]},{"kind":"content","content":[{"level":2,"text":"Return Value","type":"heading","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"The view object that’s the farthest descendent of the current view and contains point.","type":"text"},{"type":"text","text":" "},{"text":"Returns nil if the ","type":"text"},{"code":"isEventDeliveryEnabled","type":"codeVoice"},{"text":" property value is ","type":"text"},{"code":"false","type":"codeVoice"},{"type":"text","text":" and the point lies completely outside the view hierarchy of the current view."},{"text":" ","type":"text"},{"text":"Returns nil if the ","type":"text"},{"type":"codeVoice","code":"isEventDeliveryEnabled"},{"type":"text","text":" property value is "},{"code":"true","type":"codeVoice"},{"text":" and the point lies completely outside the view hierarchy of the ","type":"text"},{"code":"contentView","type":"codeVoice"},{"type":"text","text":"."}]}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/hitTest(_:with:)"},"abstract":[{"text":"Returns the farthest descendant in the view hierarchy of the current view, including itself, that contains the specified point.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD"]]},"kind":"symbol","metadata":{"symbolKind":"method","title":"hitTest(_:with:)","modules":[{"name":"LPHUD"}],"externalID":"c:@M@LPHUD@objc(cs)HUD(im)hitTest:withEvent:","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"hitTest","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@S@CGPoint","text":"CGPoint","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIEvent","preciseIdentifier":"c:objc(cs)UIEvent"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"role":"symbol","roleHeading":"Instance Method","navigatorTitle":[{"text":"hitTest:withEvent:","kind":"identifier"}]},"references":{"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUD/hitTest(_:with:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hitTest"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint","text":"CGPoint"},{"kind":"text","text":", "},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIEvent","text":"UIEvent","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/hitTest(_:with:)","url":"\/documentation\/lphud\/hud\/hittest(_:with:)","role":"symbol","kind":"symbol","abstract":[{"text":"Returns the farthest descendant in the view hierarchy of the current view, including itself, that contains the specified point.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"hitTest:withEvent:"}],"title":"hitTest(_:with:)","type":"topic"},"doc://org.cocoapods.LPHUD/documentation/LPHUD":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","kind":"symbol","url":"\/documentation\/lphud","title":"LPHUD","role":"collection","type":"topic","abstract":[]},"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUD":{"abstract":[{"text":"Displays a simple HUD window containing a progress indicator and two optional labels for short messages.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"HUD","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD","title":"HUD","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"HUD"}],"url":"\/documentation\/lphud\/hud","role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"hitTest:withEvent:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"hitTest:withEvent:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier","text":"UIView"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"hitTest:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"text":") ","kind":"text"},{"text":"point","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"withEvent:"},{"kind":"text","text":"("},{"text":"UIEvent","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIEvent"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"event"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"hitTest:withEvent:","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1HUD~1hitTest(_:with:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1HUD~1hitTest(_:with:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"hitTest:withEvent:","kind":"identifier"}]},{"op":"replace","value":"HUD","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1HUD\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1HUD\/fragments","value":[{"text":"HUD","kind":"identifier"}],"op":"replace"}]}]}