{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"didMoveToWindow","kind":"identifier"},{"text":"()","kind":"text"}]}]}],"identifier":{"url":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ActivityIndicatorView\/didMoveToWindow()","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD","doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ActivityIndicatorView"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"didMoveToWindow"}],"modules":[{"name":"FlyHUD"}],"role":"symbol","externalID":"c:@M@FlyHUD@objc(cs)ActivityIndicatorView(im)didMoveToWindow","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"didMoveToWindow","kind":"identifier"},{"kind":"text","text":"()"}],"title":"didMoveToWindow()"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/flyhud\/activityindicatorview\/didmovetowindow()"]},{"paths":["\/documentation\/flyhud\/activityindicatorview\/didmovetowindow()"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"abstract":[{"text":"Tells the view that its window object changed.","type":"text"}],"references":{"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/ActivityIndicatorView":{"role":"symbol","title":"ActivityIndicatorView","navigatorTitle":[{"kind":"identifier","text":"ActivityIndicatorView"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ActivityIndicatorView","url":"\/documentation\/flyhud\/activityindicatorview","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ActivityIndicatorView"}],"abstract":[{"type":"text","text":"A view that shows that a task is in progress."}],"type":"topic"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/ActivityIndicatorView/didMoveToWindow()":{"identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ActivityIndicatorView\/didMoveToWindow()","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"didMoveToWindow","kind":"identifier"},{"text":"()","kind":"text"}],"abstract":[{"text":"Tells the view that its window object changed.","type":"text"}],"title":"didMoveToWindow()","type":"topic","role":"symbol","navigatorTitle":[{"text":"didMoveToWindow","kind":"identifier"}],"url":"\/documentation\/flyhud\/activityindicatorview\/didmovetowindow()"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD":{"type":"topic","identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD","kind":"symbol","abstract":[],"url":"\/documentation\/flyhud","role":"collection","title":"FlyHUD"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"didMoveToWindow"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didMoveToWindow"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"didMoveToWindow"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1ActivityIndicatorView\/title","op":"replace","value":"ActivityIndicatorView"},{"path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1ActivityIndicatorView\/fragments","value":[{"text":"ActivityIndicatorView","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"didMoveToWindow","path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1ActivityIndicatorView~1didMoveToWindow()\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1ActivityIndicatorView~1didMoveToWindow()\/fragments","value":[{"kind":"text","text":"- "},{"text":"didMoveToWindow","kind":"identifier"}]}]}]}