{"metadata":{"role":"symbol","title":"indicator(_:)","roleHeading":"Type Method","modules":[{"name":"FlyHUD"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"indicator"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@FlyHUD@objc(cs)ActivityIndicatorView","text":"ActivityIndicatorView","kind":"typeIdentifier"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:6FlyHUD21ActivityIndicatorViewC5StyleO","text":"Style"},{"text":") -> ","kind":"text"},{"text":"ContentView","kind":"typeIdentifier","preciseIdentifier":"c:@M@FlyHUD@objc(cs)ContentView"},{"text":".","kind":"text"},{"text":"Mode","kind":"typeIdentifier","preciseIdentifier":"s:6FlyHUD11ContentViewC4ModeO"}],"symbolKind":"method","externalID":"s:6FlyHUD11ContentViewC4ModeO9indicatoryAeA017ActivityIndicatorD0C5StyleOFZ","extendedModule":"FlyHUD"},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ContentView\/Mode-swift.enum\/indicator(_:)-89ep2","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD","doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ContentView","doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ContentView\/Mode-swift.enum"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"indicator","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"style"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@FlyHUD@objc(cs)ActivityIndicatorView","identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ActivityIndicatorView","kind":"typeIdentifier","text":"ActivityIndicatorView"},{"text":".","kind":"text"},{"text":"Style","preciseIdentifier":"s:6FlyHUD21ActivityIndicatorViewC5StyleO","identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ActivityIndicatorView\/Style-swift.enum","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@FlyHUD@objc(cs)ContentView","text":"ContentView","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ContentView"},{"text":".","kind":"text"},{"text":"Mode","preciseIdentifier":"s:6FlyHUD11ContentViewC4ModeO","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ContentView\/Mode-swift.enum"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"A constant that specifies the style of the object to be created. See ActivityIndicatorView.Style for descriptions of the style constants.","type":"text"}],"type":"paragraph"}],"name":"style"}]},{"kind":"content","content":[{"text":"Return Value","type":"heading","anchor":"return-value","level":2},{"inlineContent":[{"text":"An initialized ContentView.Mode constant.","type":"text"}],"type":"paragraph"}]}],"variants":[{"paths":["\/documentation\/flyhud\/contentview\/mode-swift.enum\/indicator(_:)-89ep2"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Creates an activity indicator view with the specified style.","type":"text"}],"references":{"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/ContentView/Mode-swift.enum":{"title":"ContentView.Mode","url":"\/documentation\/flyhud\/contentview\/mode-swift.enum","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Mode"}],"identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ContentView\/Mode-swift.enum","abstract":[],"role":"symbol","navigatorTitle":[{"text":"Mode","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/ActivityIndicatorView/Style-swift.enum":{"type":"topic","title":"ActivityIndicatorView.Style","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"Style","kind":"identifier"}],"url":"\/documentation\/flyhud\/activityindicatorview\/style-swift.enum","identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ActivityIndicatorView\/Style-swift.enum","navigatorTitle":[{"kind":"identifier","text":"Style"}],"abstract":[{"type":"text","text":"The visual style of the activity indicator."}],"role":"symbol"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/ActivityIndicatorView":{"url":"\/documentation\/flyhud\/activityindicatorview","title":"ActivityIndicatorView","abstract":[{"type":"text","text":"A view that shows that a task is in progress."}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"ActivityIndicatorView","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ActivityIndicatorView"}],"identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ActivityIndicatorView"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/ContentView":{"url":"\/documentation\/flyhud\/contentview","kind":"symbol","type":"topic","navigatorTitle":[{"text":"ContentView","kind":"identifier"}],"title":"ContentView","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ContentView","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ContentView","role":"symbol","abstract":[{"text":"The content view of the HUD object. The view containing the labels, button and indicator (or customView).","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"The HUD object places the content in this view in front of any background views."}]},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD":{"type":"topic","url":"\/documentation\/flyhud","abstract":[],"kind":"symbol","role":"collection","title":"FlyHUD","identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/ContentView/Mode-swift.enum/indicator(_:)-89ep2":{"url":"\/documentation\/flyhud\/contentview\/mode-swift.enum\/indicator(_:)-89ep2","kind":"symbol","abstract":[{"type":"text","text":"Creates an activity indicator view with the specified style."}],"type":"topic","identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ContentView\/Mode-swift.enum\/indicator(_:)-89ep2","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"indicator"},{"text":"(","kind":"text"},{"text":"ActivityIndicatorView","preciseIdentifier":"c:@M@FlyHUD@objc(cs)ActivityIndicatorView","kind":"typeIdentifier"},{"kind":"text","text":"."},{"text":"Style","kind":"typeIdentifier","preciseIdentifier":"s:6FlyHUD21ActivityIndicatorViewC5StyleO"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@FlyHUD@objc(cs)ContentView","text":"ContentView"},{"text":".","kind":"text"},{"preciseIdentifier":"s:6FlyHUD11ContentViewC4ModeO","text":"Mode","kind":"typeIdentifier"}],"title":"indicator(_:)","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1ActivityIndicatorView\/title","value":"ActivityIndicatorView"},{"value":[{"kind":"identifier","text":"ActivityIndicatorView"}],"path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1ActivityIndicatorView\/fragments","op":"replace"},{"op":"replace","value":"ContentView","path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1ContentView\/title"},{"value":[{"kind":"identifier","text":"ContentView"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1ContentView\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}