{"variants":[{"paths":["\/documentation\/flyhud\/contentview\/mode-swift.enum\/progress(_:)-102qu"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ContentView\/Mode-swift.enum\/progress(_:)-102qu"},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"externalID":"s:6FlyHUD11ContentViewC4ModeO8progressyAeA08ProgressD0C5StyleOFZ","title":"progress(_:)","modules":[{"name":"FlyHUD"}],"extendedModule":"FlyHUD","symbolKind":"method","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"progress","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@FlyHUD@objc(cs)ProgressView","kind":"typeIdentifier","text":"ProgressView"},{"text":".","kind":"text"},{"text":"Style","kind":"typeIdentifier","preciseIdentifier":"s:6FlyHUD12ProgressViewC5StyleO"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@FlyHUD@objc(cs)ContentView","kind":"typeIdentifier","text":"ContentView"},{"kind":"text","text":"."},{"text":"Mode","preciseIdentifier":"s:6FlyHUD11ContentViewC4ModeO","kind":"typeIdentifier"}],"role":"symbol","roleHeading":"Type Method"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"progress"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"style"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ProgressView","preciseIdentifier":"c:@M@FlyHUD@objc(cs)ProgressView","identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ProgressView"},{"text":".","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ProgressView\/Style-swift.enum","kind":"typeIdentifier","text":"Style","preciseIdentifier":"s:6FlyHUD12ProgressViewC5StyleO"},{"text":") -> ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ContentView","kind":"typeIdentifier","text":"ContentView","preciseIdentifier":"c:@M@FlyHUD@objc(cs)ContentView"},{"text":".","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ContentView\/Mode-swift.enum","text":"Mode","preciseIdentifier":"s:6FlyHUD11ContentViewC4ModeO","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"A constant that specifies the style of the object to be created."},{"text":" ","type":"text"},{"text":"See ProgressView.Style for descriptions of the style constants.","type":"text"}],"type":"paragraph"}],"name":"style"}]},{"content":[{"text":"Return Value","anchor":"return-value","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"text":"An initialized ContentView.Mode constant.","type":"text"}]}],"kind":"content"}],"kind":"symbol","abstract":[{"type":"text","text":"Creates a progress view with the specified style."}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD","doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ContentView","doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ContentView\/Mode-swift.enum"]]},"references":{"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/ContentView":{"url":"\/documentation\/flyhud\/contentview","kind":"symbol","type":"topic","navigatorTitle":[{"text":"ContentView","kind":"identifier"}],"title":"ContentView","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ContentView","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ContentView","role":"symbol","abstract":[{"text":"The content view of the HUD object. The view containing the labels, button and indicator (or customView).","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"The HUD object places the content in this view in front of any background views."}]},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/ContentView/Mode-swift.enum/progress(_:)-102qu":{"title":"progress(_:)","url":"\/documentation\/flyhud\/contentview\/mode-swift.enum\/progress(_:)-102qu","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"progress"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@FlyHUD@objc(cs)ProgressView","text":"ProgressView","kind":"typeIdentifier"},{"text":".","kind":"text"},{"kind":"typeIdentifier","text":"Style","preciseIdentifier":"s:6FlyHUD12ProgressViewC5StyleO"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@FlyHUD@objc(cs)ContentView","text":"ContentView","kind":"typeIdentifier"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:6FlyHUD11ContentViewC4ModeO","text":"Mode"}],"identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ContentView\/Mode-swift.enum\/progress(_:)-102qu","kind":"symbol","abstract":[{"type":"text","text":"Creates a progress view with the specified style."}],"type":"topic","role":"symbol"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/ProgressView":{"title":"ProgressView","url":"\/documentation\/flyhud\/progressview","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProgressView"}],"identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ProgressView","abstract":[{"type":"text","text":"A view that depicts the progress of a task over time."}],"role":"symbol","navigatorTitle":[{"text":"ProgressView","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/ContentView/Mode-swift.enum":{"title":"ContentView.Mode","url":"\/documentation\/flyhud\/contentview\/mode-swift.enum","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Mode"}],"identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ContentView\/Mode-swift.enum","abstract":[],"role":"symbol","navigatorTitle":[{"text":"Mode","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/ProgressView/Style-swift.enum":{"kind":"symbol","title":"ProgressView.Style","navigatorTitle":[{"kind":"identifier","text":"Style"}],"abstract":[{"text":"The styles permitted for the progress bar.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ProgressView\/Style-swift.enum","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"Style","kind":"identifier"}],"url":"\/documentation\/flyhud\/progressview\/style-swift.enum","type":"topic"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD":{"type":"topic","url":"\/documentation\/flyhud","abstract":[],"kind":"symbol","role":"collection","title":"FlyHUD","identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1ContentView\/title","op":"replace","value":"ContentView"},{"path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1ContentView\/fragments","op":"replace","value":[{"text":"ContentView","kind":"identifier"}]},{"op":"replace","value":"ProgressView","path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1ProgressView\/title"},{"value":[{"kind":"identifier","text":"ProgressView"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1ProgressView\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}