{"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/RoundedButton\/setTitleColor(_:for:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/RoundedButton"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setTitleColor"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"color","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"for"},{"text":" ","kind":"text"},{"text":"state","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIControl","text":"UIControl","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"State","preciseIdentifier":"c:@E@UIControlState","kind":"typeIdentifier"},{"kind":"text","text":")"}],"platforms":["iOS"]}]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setTitleColor"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"text":"?, ","kind":"text"},{"text":"for","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UIControlState","text":"State"},{"text":")","kind":"text"}],"modules":[{"name":"LPHUD"}],"role":"symbol","roleHeading":"Instance Method","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"setTitleColor:forState:"}],"externalID":"c:@M@LPHUD@objc(cs)RoundedButton(im)setTitleColor:forState:","title":"setTitleColor(_:for:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/lphud\/roundedbutton\/settitlecolor(_:for:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/lphud\/roundedbutton\/settitlecolor(_:for:)"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://org.cocoapods.LPHUD/documentation/LPHUD/RoundedButton/setTitleColor(_:for:)":{"navigatorTitle":[{"text":"setTitleColor:forState:","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/RoundedButton\/setTitleColor(_:for:)","abstract":[],"type":"topic","url":"\/documentation\/lphud\/roundedbutton\/settitlecolor(_:for:)","title":"setTitleColor(_:for:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setTitleColor","kind":"identifier"},{"kind":"text","text":"("},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIControl","text":"UIControl"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@UIControlState","text":"State","kind":"typeIdentifier"},{"kind":"text","text":")"}],"kind":"symbol"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/RoundedButton":{"navigatorTitle":[{"kind":"identifier","text":"RoundedButton"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/RoundedButton","abstract":[],"type":"topic","url":"\/documentation\/lphud\/roundedbutton","title":"RoundedButton","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"RoundedButton","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.LPHUD/documentation/LPHUD":{"abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","url":"\/documentation\/lphud","kind":"symbol","title":"LPHUD"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"setTitleColor:forState:","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setTitleColor:forState:"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"setTitleColor:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"color"},{"text":" ","kind":"text"},{"text":"forState:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@UIControlState","text":"UIControlState","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"state","kind":"internalParam"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"setTitleColor:forState:","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1RoundedButton~1setTitleColor(_:for:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1RoundedButton~1setTitleColor(_:for:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setTitleColor:forState:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1RoundedButton\/title","value":"RoundedButton"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1RoundedButton\/fragments","value":[{"text":"RoundedButton","kind":"identifier"}]}]}]}