{"abstract":[{"type":"text","text":"Creates a progress view with the specified style."}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView\/Mode-swift.enum"]]},"metadata":{"extendedModule":"LPHUD","title":"progress(_:)","externalID":"s:5LPHUD11ContentViewC4ModeO8progressyAeA08ProgressC0C5StyleOFZ","modules":[{"name":"LPHUD"}],"symbolKind":"method","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"progress","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ProgressView","preciseIdentifier":"c:@M@LPHUD@objc(cs)ProgressView","kind":"typeIdentifier"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:5LPHUD12ProgressViewC5StyleO","text":"Style"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"ContentView","preciseIdentifier":"c:@M@LPHUD@objc(cs)ContentView"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:5LPHUD11ContentViewC4ModeO","text":"Mode"}],"roleHeading":"Type Method"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView\/Mode-swift.enum\/progress(_:)-3wvhv"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"progress"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"style","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"ProgressView","preciseIdentifier":"c:@M@LPHUD@objc(cs)ProgressView","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView","kind":"typeIdentifier"},{"kind":"text","text":"."},{"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView\/Style-swift.enum","kind":"typeIdentifier","text":"Style","preciseIdentifier":"s:5LPHUD12ProgressViewC5StyleO"},{"text":") -> ","kind":"text"},{"text":"ContentView","kind":"typeIdentifier","preciseIdentifier":"c:@M@LPHUD@objc(cs)ContentView","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView"},{"text":".","kind":"text"},{"kind":"typeIdentifier","text":"Mode","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView\/Mode-swift.enum","preciseIdentifier":"s:5LPHUD11ContentViewC4ModeO"}]}]},{"parameters":[{"content":[{"inlineContent":[{"text":"A constant that specifies the style of the object to be created.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"See ProgressView.Style for descriptions of the style constants."}],"type":"paragraph"}],"name":"style"}],"kind":"parameters"},{"content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"text":"An initialized ContentView.Mode constant.","type":"text"}]}],"kind":"content"}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/lphud\/contentview\/mode-swift.enum\/progress(_:)-3wvhv"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://org.cocoapods.LPHUD/documentation/LPHUD/ContentView":{"type":"topic","title":"ContentView","navigatorTitle":[{"kind":"identifier","text":"ContentView"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ContentView","kind":"identifier"}],"abstract":[{"type":"text","text":"The content view of the HUD object. The view containing the labels, button and indicator (or customView)."},{"text":" ","type":"text"},{"text":"The HUD object places the content in this view in front of any background views.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView","kind":"symbol","role":"symbol","url":"\/documentation\/lphud\/contentview"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ProgressView":{"type":"topic","title":"ProgressView","navigatorTitle":[{"kind":"identifier","text":"ProgressView"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProgressView"}],"abstract":[{"type":"text","text":"A view that depicts the progress of a task over time."}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView","kind":"symbol","role":"symbol","url":"\/documentation\/lphud\/progressview"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ContentView/Mode-swift.enum/progress(_:)-3wvhv":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView\/Mode-swift.enum\/progress(_:)-3wvhv","title":"progress(_:)","url":"\/documentation\/lphud\/contentview\/mode-swift.enum\/progress(_:)-3wvhv","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"progress","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ProgressView","preciseIdentifier":"c:@M@LPHUD@objc(cs)ProgressView"},{"text":".","kind":"text"},{"kind":"typeIdentifier","text":"Style","preciseIdentifier":"s:5LPHUD12ProgressViewC5StyleO"},{"text":") -> ","kind":"text"},{"text":"ContentView","preciseIdentifier":"c:@M@LPHUD@objc(cs)ContentView","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:5LPHUD11ContentViewC4ModeO","text":"Mode","kind":"typeIdentifier"}],"abstract":[{"text":"Creates a progress view with the specified style.","type":"text"}]},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ContentView/Mode-swift.enum":{"title":"ContentView.Mode","role":"symbol","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView\/Mode-swift.enum","navigatorTitle":[{"kind":"identifier","text":"Mode"}],"type":"topic","kind":"symbol","url":"\/documentation\/lphud\/contentview\/mode-swift.enum","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Mode","kind":"identifier"}],"abstract":[]},"doc://org.cocoapods.LPHUD/documentation/LPHUD":{"role":"collection","kind":"symbol","abstract":[],"title":"LPHUD","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","type":"topic","url":"\/documentation\/lphud"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ProgressView/Style-swift.enum":{"url":"\/documentation\/lphud\/progressview\/style-swift.enum","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Style"}],"abstract":[{"type":"text","text":"The styles permitted for the progress bar."}],"navigatorTitle":[{"kind":"identifier","text":"Style"}],"title":"ProgressView.Style","kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView\/Style-swift.enum"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ContentView\/title","value":"ContentView","op":"replace"},{"value":[{"kind":"identifier","text":"ContentView"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ContentView\/fragments"},{"value":"ProgressView","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ProgressView\/title"},{"value":[{"text":"ProgressView","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ProgressView\/fragments","op":"replace"}]}]}