{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"lazy","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"button"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@LPHUD@objc(cs)Button","text":"Button","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Button"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/lphud\/contentview\/button"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"modules":[{"name":"LPHUD"}],"externalID":"s:5LPHUD11ContentViewC6buttonAA6ButtonCvp","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"button"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@LPHUD@objc(cs)Button","text":"Button","kind":"typeIdentifier"}],"symbolKind":"property","role":"symbol","title":"button"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"abstract":[{"type":"text","text":"A button that is placed below the labels. Visible only if a target \/ action is added and a title is assigned."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView\/button"},"references":{"doc://org.cocoapods.LPHUD/documentation/LPHUD/ContentView/button":{"abstract":[{"type":"text","text":"A button that is placed below the labels. Visible only if a target \/ action is added and a title is assigned."}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView\/button","type":"topic","kind":"symbol","title":"button","url":"\/documentation\/lphud\/contentview\/button","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"button"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@LPHUD@objc(cs)Button","text":"Button","kind":"typeIdentifier"}]},"doc://org.cocoapods.LPHUD/documentation/LPHUD":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","kind":"symbol","url":"\/documentation\/lphud","title":"LPHUD","role":"collection","type":"topic","abstract":[]},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ContentView":{"title":"ContentView","type":"topic","role":"symbol","abstract":[{"text":"The content view of the HUD object. The view containing the labels, button and indicator (or customView).","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"The HUD object places the content in this view in front of any background views."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ContentView"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView","url":"\/documentation\/lphud\/contentview","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ContentView","kind":"identifier"}]},"doc://org.cocoapods.LPHUD/documentation/LPHUD/Button":{"role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Button","url":"\/documentation\/lphud\/button","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Button"}],"navigatorTitle":[{"text":"Button","kind":"identifier"}],"title":"Button","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ContentView\/title","value":"ContentView"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ContentView\/fragments","value":[{"text":"ContentView","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1Button\/title","value":"Button"},{"value":[{"text":"Button","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1Button\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}