{"abstract":[{"text":"A progress view for showing definite progress by filling up a circle (pie chart).","type":"text"}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/RoundProgressView\/init()","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/RoundProgressView\/init(coder:)","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/RoundProgressView\/init(frame:)"]},{"identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/RoundProgressView\/backgroundTintColor","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/RoundProgressView\/intrinsicContentSize","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/RoundProgressView\/isAnnular","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/RoundProgressView\/progress","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/RoundProgressView\/progressTintColor"],"title":"Instance Properties"},{"identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/RoundProgressView\/draw(_:)"],"title":"Instance Methods"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RoundProgressView"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/lphud\/roundprogressview"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/lphud\/roundprogressview"]}],"metadata":{"symbolKind":"class","navigatorTitle":[{"kind":"identifier","text":"RoundProgressView"}],"externalID":"c:@M@LPHUD@objc(cs)RoundProgressView","title":"RoundProgressView","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"RoundProgressView","kind":"identifier"}],"roleHeading":"Class","modules":[{"name":"LPHUD"}]},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/RoundProgressView"},"sections":[],"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.LPHUD\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From"},{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.LPHUD\/objc(pl)NSCoding","doc:\/\/org.cocoapods.LPHUD\/objc(pl)NSObject","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Progressive","doc:\/\/org.cocoapods.LPHUD\/objc(pl)CALayerDelegate","doc:\/\/org.cocoapods.LPHUD\/s7CVarArgP","doc:\/\/org.cocoapods.LPHUD\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.LPHUD\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.LPHUD\/SQ","doc:\/\/org.cocoapods.LPHUD\/SH","doc:\/\/org.cocoapods.LPHUD\/s8SendableP","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIAccessibilityIdentification","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIAppearance","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UICoordinateSpace","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIDynamicItem","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIFocusItem","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIFocusItemContainer","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UILargeContentViewerItem","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.LPHUD\/5UIKit23UITraitChangeObservableP","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIUserActivityRestoring"]}],"references":{"doc://org.cocoapods.LPHUD/documentation/LPHUD/RoundProgressView/backgroundTintColor":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"backgroundTintColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"url":"\/documentation\/lphud\/roundprogressview\/backgroundtintcolor","abstract":[{"type":"text","text":"Indicator background (non-progress) color. Defaults to translucent white (alpha 0.1)."}],"role":"symbol","title":"backgroundTintColor","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/RoundProgressView\/backgroundTintColor","kind":"symbol"},"doc://org.cocoapods.LPHUD/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIResponderStandardEditActions","title":"UIKit.UIResponderStandardEditActions"},"doc://org.cocoapods.LPHUD/objc(pl)UIUserActivityRestoring":{"title":"UIKit.UIUserActivityRestoring","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIUserActivityRestoring"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/RoundProgressView/init(coder:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"title":"init(coder:)","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/RoundProgressView\/init(coder:)","url":"\/documentation\/lphud\/roundprogressview\/init(coder:)","abstract":[]},"doc://org.cocoapods.LPHUD/objc(pl)UIAppearanceContainer":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIAppearanceContainer","title":"UIKit.UIAppearanceContainer"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/Progressive":{"navigatorTitle":[{"kind":"identifier","text":"Progressive"}],"title":"Progressive","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Progressive"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Progressive","url":"\/documentation\/lphud\/progressive","abstract":[]},"doc://org.cocoapods.LPHUD/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://org.cocoapods.LPHUD/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding"},"doc://org.cocoapods.LPHUD/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIFocusItem"},"doc://org.cocoapods.LPHUD/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIPasteConfigurationSupporting"},"doc://org.cocoapods.LPHUD/SH":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/SH","title":"Swift.Hashable"},"doc://org.cocoapods.LPHUD/SQ":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/SQ","title":"Swift.Equatable"},"doc://org.cocoapods.LPHUD/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UILargeContentViewerItem","title":"UIKit.UILargeContentViewerItem"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/RoundProgressView":{"navigatorTitle":[{"text":"RoundProgressView","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RoundProgressView"}],"url":"\/documentation\/lphud\/roundprogressview","abstract":[{"type":"text","text":"A progress view for showing definite progress by filling up a circle (pie chart)."}],"role":"symbol","title":"RoundProgressView","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/RoundProgressView","kind":"symbol"},"doc://org.cocoapods.LPHUD/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/5UIKit23UITraitChangeObservableP","title":"UIKit.UITraitChangeObservable"},"doc://org.cocoapods.LPHUD/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/s8SendableP","title":"Swift.Sendable"},"doc://org.cocoapods.LPHUD/objc(pl)UIFocusEnvironment":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIFocusEnvironment","title":"UIKit.UIFocusEnvironment"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/RoundProgressView/isAnnular":{"title":"isAnnular","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isAnnular"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/RoundProgressView\/isAnnular","url":"\/documentation\/lphud\/roundprogressview\/isannular","abstract":[{"type":"text","text":"Display mode - false = round or true = annular. Defaults to round."}]},"doc://org.cocoapods.LPHUD/documentation/LPHUD/RoundProgressView/init(frame:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithFrame:"}],"title":"init(frame:)","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"kind":"text","text":")"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/RoundProgressView\/init(frame:)","url":"\/documentation\/lphud\/roundprogressview\/init(frame:)","abstract":[]},"doc://org.cocoapods.LPHUD/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIAppearance"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/RoundProgressView/draw(_:)":{"navigatorTitle":[{"kind":"identifier","text":"drawRect:"}],"title":"draw(_:)","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"draw"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":")"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/RoundProgressView\/draw(_:)","url":"\/documentation\/lphud\/roundprogressview\/draw(_:)","abstract":[]},"doc://org.cocoapods.LPHUD/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIPopoverPresentationControllerSourceItem","title":"UIKit.UIPopoverPresentationControllerSourceItem"},"doc://org.cocoapods.LPHUD/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.LPHUD/objc(pl)UIAccessibilityIdentification":{"title":"UIKit.UIAccessibilityIdentification","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIAccessibilityIdentification"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/RoundProgressView/init()":{"navigatorTitle":[{"kind":"identifier","text":"init"}],"title":"init()","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/RoundProgressView\/init()","url":"\/documentation\/lphud\/roundprogressview\/init()","abstract":[]},"doc://org.cocoapods.LPHUD/documentation/LPHUD/RoundProgressView/progressTintColor":{"title":"progressTintColor","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"progressTintColor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/RoundProgressView\/progressTintColor","url":"\/documentation\/lphud\/roundprogressview\/progresstintcolor","abstract":[{"type":"text","text":"Indicator progress color. Defaults to white UIColor.white."}]},"doc://org.cocoapods.LPHUD/documentation/LPHUD":{"type":"topic","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","title":"LPHUD","url":"\/documentation\/lphud","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.LPHUD/objc(pl)CALayerDelegate":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)CALayerDelegate","title":"QuartzCore.CALayerDelegate"},"doc://org.cocoapods.LPHUD/objc(cs)UIView":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(cs)UIView","title":"UIView"},"doc://org.cocoapods.LPHUD/objc(pl)UITraitEnvironment":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UITraitEnvironment","title":"UIKit.UITraitEnvironment"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/RoundProgressView/intrinsicContentSize":{"navigatorTitle":[{"kind":"identifier","text":"intrinsicContentSize"}],"title":"intrinsicContentSize","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"intrinsicContentSize","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier","text":"CGSize"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/RoundProgressView\/intrinsicContentSize","url":"\/documentation\/lphud\/roundprogressview\/intrinsiccontentsize","abstract":[]},"doc://org.cocoapods.LPHUD/documentation/LPHUD/RoundProgressView/progress":{"title":"progress","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"progress"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/RoundProgressView\/progress","url":"\/documentation\/lphud\/roundprogressview\/progress","abstract":[{"type":"text","text":"Progress (0.0 to 1.0)"}]},"doc://org.cocoapods.LPHUD/objc(pl)NSCoding":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)NSCoding","title":"Foundation.NSCoding"},"doc://org.cocoapods.LPHUD/objc(pl)UIFocusItemContainer":{"title":"UIKit.UIFocusItemContainer","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIFocusItemContainer"},"doc://org.cocoapods.LPHUD/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/s7CVarArgP"},"doc://org.cocoapods.LPHUD/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)NSObject"},"doc://org.cocoapods.LPHUD/objc(pl)UIDynamicItem":{"title":"UIKit.UIDynamicItem","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIDynamicItem"},"doc://org.cocoapods.LPHUD/objc(pl)UICoordinateSpace":{"title":"UIKit.UICoordinateSpace","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UICoordinateSpace"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"RoundProgressView"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"value":[{"kind":"identifier","text":"RoundProgressView"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"RoundProgressView","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/RoundProgressView\/intrinsicContentSize"],"title":"Instance Properties"},{"identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/RoundProgressView\/draw(_:)","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/RoundProgressView\/init()","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/RoundProgressView\/init(coder:)","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/RoundProgressView\/init(frame:)"],"title":"Instance Methods"}]},{"value":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.LPHUD\/objc(cs)UIView"]}],"path":"\/relationshipsSections","op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"RoundProgressView"},{"text":" : ","kind":"text"},{"text":"UIView","preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1RoundProgressView~1init(coder:)\/title","value":"initWithCoder:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1RoundProgressView~1init(coder:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithCoder:","kind":"identifier"}]},{"op":"replace","value":"RoundProgressView","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1RoundProgressView\/title"},{"value":[{"text":"RoundProgressView","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1RoundProgressView\/fragments","op":"replace"},{"value":"initWithFrame:","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1RoundProgressView~1init(frame:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1RoundProgressView~1init(frame:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithFrame:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1RoundProgressView~1draw(_:)\/title","value":"drawRect:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1RoundProgressView~1draw(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"drawRect:","kind":"identifier"}]},{"op":"replace","value":"init","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1RoundProgressView~1init()\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1RoundProgressView~1init()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1RoundProgressView~1intrinsicContentSize\/title","op":"replace","value":"intrinsicContentSize"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1RoundProgressView~1intrinsicContentSize\/fragments","value":[{"text":"intrinsicContentSize","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}