{"variants":[{"paths":["\/documentation\/lphud\/hud\/backgroundview"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"title":"backgroundView","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"backgroundView","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@LPHUD@objc(cs)BackgroundView","text":"BackgroundView"}],"externalID":"s:5LPHUD3HUDC14backgroundViewAA010BackgroundD0Cvp","role":"symbol","modules":[{"name":"LPHUD"}],"roleHeading":"Instance Property","symbolKind":"property"},"identifier":{"url":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/backgroundView","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"View covering the entire HUD area, placed behind bezelView."}],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"lazy","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"backgroundView","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"BackgroundView","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BackgroundView","preciseIdentifier":"c:@M@LPHUD@objc(cs)BackgroundView"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD"]]},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://org.cocoapods.LPHUD/documentation/LPHUD/BackgroundView":{"abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"text":"BackgroundView","kind":"identifier"}],"url":"\/documentation\/lphud\/backgroundview","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"BackgroundView","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BackgroundView","title":"BackgroundView","kind":"symbol"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUD":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HUD"}],"title":"HUD","navigatorTitle":[{"text":"HUD","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Displays a simple HUD window containing a progress indicator and two optional labels for short messages."}],"url":"\/documentation\/lphud\/hud","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD","role":"symbol"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUD/backgroundView":{"url":"\/documentation\/lphud\/hud\/backgroundview","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/backgroundView","abstract":[{"type":"text","text":"View covering the entire HUD area, placed behind bezelView."}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"backgroundView","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@LPHUD@objc(cs)BackgroundView","text":"BackgroundView"}],"type":"topic","kind":"symbol","title":"backgroundView","role":"symbol"},"doc://org.cocoapods.LPHUD/documentation/LPHUD":{"abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","url":"\/documentation\/lphud","kind":"symbol","title":"LPHUD"}},"variantOverrides":[{"patch":[{"value":"BackgroundView","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1BackgroundView\/title"},{"value":[{"text":"BackgroundView","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1BackgroundView\/fragments","op":"replace"},{"value":"HUD","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1HUD\/title","op":"replace"},{"op":"replace","value":[{"text":"HUD","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1HUD\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}