{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"updateConstraints","kind":"identifier"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/updateConstraints()"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD"]]},"variants":[{"paths":["\/documentation\/lphud\/hud\/updateconstraints()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/lphud\/hud\/updateconstraints()"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"title":"updateConstraints()","symbolKind":"method","roleHeading":"Instance Method","navigatorTitle":[{"text":"updateConstraints","kind":"identifier"}],"modules":[{"name":"LPHUD"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"updateConstraints","kind":"identifier"},{"kind":"text","text":"()"}],"externalID":"c:@M@LPHUD@objc(cs)HUD(im)updateConstraints","role":"symbol"},"references":{"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUD":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HUD"}],"title":"HUD","navigatorTitle":[{"text":"HUD","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Displays a simple HUD window containing a progress indicator and two optional labels for short messages."}],"url":"\/documentation\/lphud\/hud","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD","role":"symbol"},"doc://org.cocoapods.LPHUD/documentation/LPHUD":{"abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","url":"\/documentation\/lphud","kind":"symbol","title":"LPHUD"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUD/updateConstraints()":{"kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/updateConstraints()","navigatorTitle":[{"text":"updateConstraints","kind":"identifier"}],"title":"updateConstraints()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"updateConstraints","kind":"identifier"},{"text":"()","kind":"text"}],"url":"\/documentation\/lphud\/hud\/updateconstraints()","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"updateConstraints"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"updateConstraints","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"updateConstraints","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1HUD\/title","op":"replace","value":"HUD"},{"op":"replace","value":[{"kind":"identifier","text":"HUD"}],"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1HUD\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1HUD~1updateConstraints()\/title","value":"updateConstraints","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1HUD~1updateConstraints()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"updateConstraints","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}