{"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Creates a new HUD. adds it to provided view and shows it. And auto hides the HUD after a duration."}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@discardableResult"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"showStatus","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"text":" ","kind":"text"},{"text":"view","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"duration"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":" = 2.0, ","kind":"text"},{"kind":"externalParam","text":"using"},{"kind":"text","text":" "},{"text":"animation","kind":"internalParam"},{"kind":"text","text":": "},{"text":"Animation","kind":"typeIdentifier","preciseIdentifier":"s:5LPHUD3HUDC9AnimationV","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/Animation-swift.struct"},{"text":", ","kind":"text"},{"text":"mode","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@LPHUD@objc(cs)ContentView","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView","kind":"typeIdentifier","text":"ContentView"},{"kind":"text","text":"."},{"text":"Mode","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView\/Mode-swift.enum","preciseIdentifier":"s:5LPHUD11ContentViewC4ModeO"},{"kind":"text","text":" = .text, "},{"kind":"externalParam","text":"label"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"offset"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"text":" = .h.vMaxOffset, ","kind":"text"},{"kind":"externalParam","text":"populator"},{"kind":"text","text":": (("},{"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD","kind":"typeIdentifier","text":"HUD","preciseIdentifier":"c:@M@LPHUD@objc(cs)HUD"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")? = nil) -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD","preciseIdentifier":"c:@M@LPHUD@objc(cs)HUD","text":"HUD"}],"languages":["swift"]}]},{"parameters":[{"name":"view","content":[{"type":"paragraph","inlineContent":[{"text":"The view that the HUD will be added to","type":"text"}]}]},{"name":"duration","content":[{"inlineContent":[{"text":"The total duration of the show, measured in seconds. Duration must be greater than 0.0. ","type":"text"},{"code":"Default to 2.0","type":"codeVoice"},{"text":".","type":"text"}],"type":"paragraph"}]},{"name":"animation","content":[{"type":"paragraph","inlineContent":[{"text":"Use HUD.Animation.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"HUD operation mode. "},{"code":"Default to .indicator(.large)","type":"codeVoice"},{"type":"text","text":"."}]}],"name":"mode"},{"name":"label","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An optional short message to be displayed below the activity indicator. The HUD is automatically resized to fit the entire text."},{"type":"text","text":" "},{"text":"If the text is too long it will get clipped by displaying “…” at the end. If left unchanged or set to “”, then no message is displayed.","type":"text"}]}]},{"name":"offset","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The contentView offset relative to the center of the view. You can use "},{"type":"codeVoice","code":".maxOffset"},{"type":"text","text":" to move the HUD all the way to"},{"text":" ","type":"text"},{"type":"text","text":"the screen edge in each direction. "},{"code":"Default to .vMaxOffset","type":"codeVoice"},{"text":".","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A block or function that populates the "},{"type":"codeVoice","code":"HUD"},{"text":", which is passed into the block as an argument. ","type":"text"},{"type":"codeVoice","code":"Default to nil"},{"type":"text","text":"."}]}],"name":"populator"}],"kind":"parameters"},{"kind":"content","content":[{"text":"Return Value","anchor":"return-value","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"A reference to the created HUD."}]}]},{"kind":"content","content":[{"anchor":"discussion","text":"Discussion","level":2,"type":"heading"},{"style":"note","type":"aside","name":"Note","content":[{"inlineContent":[{"text":"If ","type":"text"},{"type":"codeVoice","code":"isCountEnabled"},{"text":" is set to true, the activity count is incremented by 1 when showing the HUD. The activity count is decremented by 1 when hiding the HUD.","type":"text"}],"type":"paragraph"}]}]}],"variants":[{"paths":["\/documentation\/lphud\/hud\/showstatus(to:duration:using:mode:label:offset:populator:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/showStatus(to:duration:using:mode:label:offset:populator:)","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"showStatus","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"to"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier","text":"UIView"},{"text":", ","kind":"text"},{"text":"duration","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":", "},{"text":"using","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:5LPHUD3HUDC9AnimationV","text":"Animation","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"mode","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ContentView","preciseIdentifier":"c:@M@LPHUD@objc(cs)ContentView"},{"kind":"text","text":"."},{"preciseIdentifier":"s:5LPHUD11ContentViewC4ModeO","text":"Mode","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"label","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"text":"offset","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CGPoint","preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"populator"},{"text":": ((","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@LPHUD@objc(cs)HUD","text":"HUD"},{"kind":"text","text":") -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@LPHUD@objc(cs)HUD","text":"HUD"}],"externalID":"s:5LPHUD3HUDC10showStatus2to8duration5using4mode5label6offset9populatorACSo6UIViewC_SdAC9AnimationVAA11ContentViewC4ModeOSSSgSo7CGPointVyACcSgtFZ","roleHeading":"Type Method","modules":[{"name":"LPHUD"}],"symbolKind":"method","title":"showStatus(to:duration:using:mode:label:offset:populator:)"},"references":{"doc://org.cocoapods.LPHUD/documentation/LPHUD/ContentView":{"type":"topic","title":"ContentView","navigatorTitle":[{"kind":"identifier","text":"ContentView"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ContentView","kind":"identifier"}],"abstract":[{"type":"text","text":"The content view of the HUD object. The view containing the labels, button and indicator (or customView)."},{"text":" ","type":"text"},{"text":"The HUD object places the content in this view in front of any background views.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView","kind":"symbol","role":"symbol","url":"\/documentation\/lphud\/contentview"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUD":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"HUD"}],"kind":"symbol","abstract":[{"text":"Displays a simple HUD window containing a progress indicator and two optional labels for short messages.","type":"text"}],"url":"\/documentation\/lphud\/hud","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD","role":"symbol","title":"HUD","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"HUD","kind":"identifier"}]},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ContentView/Mode-swift.enum":{"title":"ContentView.Mode","role":"symbol","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ContentView\/Mode-swift.enum","navigatorTitle":[{"kind":"identifier","text":"Mode"}],"type":"topic","kind":"symbol","url":"\/documentation\/lphud\/contentview\/mode-swift.enum","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Mode","kind":"identifier"}],"abstract":[]},"doc://org.cocoapods.LPHUD/documentation/LPHUD":{"role":"collection","kind":"symbol","abstract":[],"title":"LPHUD","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","type":"topic","url":"\/documentation\/lphud"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUD/Animation-swift.struct":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/Animation-swift.struct","title":"HUD.Animation","navigatorTitle":[{"kind":"identifier","text":"Animation"}],"url":"\/documentation\/lphud\/hud\/animation-swift.struct","role":"symbol","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Animation","kind":"identifier"}],"abstract":[],"type":"topic"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUD/showStatus(to:duration:using:mode:label:offset:populator:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/showStatus(to:duration:using:mode:label:offset:populator:)","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"showStatus","kind":"identifier"},{"kind":"text","text":"("},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"duration","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"using"},{"text":": ","kind":"text"},{"text":"Animation","preciseIdentifier":"s:5LPHUD3HUDC9AnimationV","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"mode","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@LPHUD@objc(cs)ContentView","kind":"typeIdentifier","text":"ContentView"},{"text":".","kind":"text"},{"kind":"typeIdentifier","text":"Mode","preciseIdentifier":"s:5LPHUD11ContentViewC4ModeO"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"label"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"offset","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint","text":"CGPoint"},{"kind":"text","text":", "},{"text":"populator","kind":"externalParam"},{"kind":"text","text":": (("},{"preciseIdentifier":"c:@M@LPHUD@objc(cs)HUD","kind":"typeIdentifier","text":"HUD"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"HUD","preciseIdentifier":"c:@M@LPHUD@objc(cs)HUD"}],"url":"\/documentation\/lphud\/hud\/showstatus(to:duration:using:mode:label:offset:populator:)","role":"symbol","abstract":[{"type":"text","text":"Creates a new HUD. adds it to provided view and shows it. And auto hides the HUD after a duration."}],"title":"showStatus(to:duration:using:mode:label:offset:populator:)","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ContentView\/title","value":"ContentView"},{"op":"replace","value":[{"text":"ContentView","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ContentView\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1HUD\/title","value":"HUD","op":"replace"},{"value":[{"kind":"identifier","text":"HUD"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1HUD\/fragments"}]}]}