{"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"BackgroundView","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/BackgroundView"},"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/BaseView"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"kind":"relationships","type":"inheritedBy","identifiers":["doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ContentView"],"title":"Inherited By"},{"identifiers":["doc:\/\/org.cocoapods.FlyHUD\/objc(pl)NSCoding","doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/HUDExtended","doc:\/\/org.cocoapods.FlyHUD\/objc(pl)NSObject","doc:\/\/org.cocoapods.FlyHUD\/objc(pl)CALayerDelegate","doc:\/\/org.cocoapods.FlyHUD\/s7CVarArgP","doc:\/\/org.cocoapods.FlyHUD\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.FlyHUD\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.FlyHUD\/SQ","doc:\/\/org.cocoapods.FlyHUD\/SH","doc:\/\/org.cocoapods.FlyHUD\/s8SendableP","doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIAccessibilityIdentification","doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIAppearance","doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UICoordinateSpace","doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIDynamicItem","doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIFocusItem","doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIFocusItemContainer","doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UILargeContentViewerItem","doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.FlyHUD\/5UIKit23UITraitChangeObservableP","doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIUserActivityRestoring"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/BackgroundView\/color","doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/BackgroundView\/intrinsicContentSize","doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/BackgroundView\/roundedCorners","doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/BackgroundView\/style-swift.property"],"title":"Instance Properties"},{"identifiers":["doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/BackgroundView\/commonInit()","doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/BackgroundView\/layoutSubviews()"],"title":"Instance Methods"},{"identifiers":["doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/BackgroundView\/Style-swift.enum"],"title":"Enumerations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/flyhud\/backgroundview"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/flyhud\/backgroundview"]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"BackgroundView"}],"modules":[{"name":"FlyHUD"}],"externalID":"c:@M@FlyHUD@objc(cs)BackgroundView","roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BackgroundView"}],"role":"symbol","title":"BackgroundView","symbolKind":"class"},"abstract":[{"type":"text","text":"The view to use as the background of the HUD."},{"type":"text","text":" "},{"text":"HUD adds the background view as a subview behind all other views and uses its current frame location.","type":"text"}],"references":{"doc://org.cocoapods.FlyHUD/objc(pl)UIAppearance":{"identifier":"doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIAppearance","title":"UIKit.UIAppearance","type":"unresolvable"},"doc://org.cocoapods.FlyHUD/objc(pl)UIPopoverPresentationControllerSourceItem":{"identifier":"doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIPopoverPresentationControllerSourceItem","type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/BackgroundView":{"type":"topic","title":"BackgroundView","abstract":[{"type":"text","text":"The view to use as the background of the HUD."},{"type":"text","text":" "},{"type":"text","text":"HUD adds the background view as a subview behind all other views and uses its current frame location."}],"role":"symbol","url":"\/documentation\/flyhud\/backgroundview","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"BackgroundView"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"BackgroundView","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/BackgroundView"},"doc://org.cocoapods.FlyHUD/5UIKit23UITraitChangeObservableP":{"identifier":"doc:\/\/org.cocoapods.FlyHUD\/5UIKit23UITraitChangeObservableP","type":"unresolvable","title":"UIKit.UITraitChangeObservable"},"doc://org.cocoapods.FlyHUD/objc(pl)CALayerDelegate":{"identifier":"doc:\/\/org.cocoapods.FlyHUD\/objc(pl)CALayerDelegate","type":"unresolvable","title":"QuartzCore.CALayerDelegate"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/ContentView":{"url":"\/documentation\/flyhud\/contentview","kind":"symbol","type":"topic","navigatorTitle":[{"text":"ContentView","kind":"identifier"}],"title":"ContentView","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ContentView","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ContentView","role":"symbol","abstract":[{"text":"The content view of the HUD object. The view containing the labels, button and indicator (or customView).","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"The HUD object places the content in this view in front of any background views."}]},"doc://org.cocoapods.FlyHUD/objc(pl)UIUserActivityRestoring":{"identifier":"doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIUserActivityRestoring","type":"unresolvable","title":"UIKit.UIUserActivityRestoring"},"doc://org.cocoapods.FlyHUD/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.FlyHUD\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/BackgroundView/roundedCorners":{"role":"symbol","title":"roundedCorners","identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/BackgroundView\/roundedCorners","url":"\/documentation\/flyhud\/backgroundview\/roundedcorners","type":"topic","abstract":[{"type":"text","text":"The rounded corner mode of the button. "},{"type":"codeVoice","code":"Default to .radius(0.0)"},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"roundedCorners","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:6FlyHUD14RoundedCornersO","text":"RoundedCorners"}],"kind":"symbol"},"doc://org.cocoapods.FlyHUD/objc(pl)UITraitEnvironment":{"identifier":"doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UITraitEnvironment","type":"unresolvable","title":"UIKit.UITraitEnvironment"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/BackgroundView/style-swift.property":{"identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/BackgroundView\/style-swift.property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"style"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:6FlyHUD14BackgroundViewC5StyleO","text":"Style"}],"kind":"symbol","role":"symbol","title":"style","url":"\/documentation\/flyhud\/backgroundview\/style-swift.property","type":"topic","abstract":[{"type":"text","text":"The background style. "},{"code":"Defaults to .solidColor","type":"codeVoice"},{"type":"text","text":"."}]},"doc://org.cocoapods.FlyHUD/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding"},"doc://org.cocoapods.FlyHUD/objc(pl)UIFocusItemContainer":{"identifier":"doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIFocusItemContainer","title":"UIKit.UIFocusItemContainer","type":"unresolvable"},"doc://org.cocoapods.FlyHUD/objc(pl)UICoordinateSpace":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UICoordinateSpace","title":"UIKit.UICoordinateSpace"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/BackgroundView/color":{"identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/BackgroundView\/color","kind":"symbol","title":"color","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"color","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"text":"?","kind":"text"}],"abstract":[{"text":"The background color or the blur tint color. ","type":"text"},{"code":"Defaults to .clear","type":"codeVoice"},{"text":".","type":"text"}],"role":"symbol","url":"\/documentation\/flyhud\/backgroundview\/color"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/BackgroundView/initWithCoder:":{"identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/BackgroundView\/initWithCoder:","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithCoder:"}],"kind":"symbol","role":"symbol","title":"initWithCoder:","url":"\/documentation\/flyhud\/backgroundview\/initwithcoder:","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}]},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/BackgroundView/layoutSubviews()":{"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"layoutSubviews"}],"title":"layoutSubviews()","url":"\/documentation\/flyhud\/backgroundview\/layoutsubviews()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"layoutSubviews"},{"kind":"text","text":"()"}],"type":"topic","abstract":[{"type":"text","text":"Lays out subviews."}],"identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/BackgroundView\/layoutSubviews()"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/BaseView":{"identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/BaseView","kind":"symbol","url":"\/documentation\/flyhud\/baseview","title":"BaseView","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BaseView"}],"abstract":[{"type":"text","text":"A base view only provides one "},{"code":"commonInit","type":"codeVoice"},{"text":" method.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BaseView"}]},"doc://org.cocoapods.FlyHUD/SH":{"identifier":"doc:\/\/org.cocoapods.FlyHUD\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/HUDExtended":{"title":"HUDExtended","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HUDExtended"}],"kind":"symbol","url":"\/documentation\/flyhud\/hudextended","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HUDExtended","kind":"identifier"}],"abstract":[{"type":"text","text":"Protocol describing the "},{"type":"codeVoice","code":"h"},{"type":"text","text":" extension points for HUD extended types."}],"identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/HUDExtended"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/BackgroundView/Style-swift.enum":{"type":"topic","title":"BackgroundView.Style","abstract":[],"role":"symbol","url":"\/documentation\/flyhud\/backgroundview\/style-swift.enum","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Style"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"Style","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/BackgroundView\/Style-swift.enum"},"doc://org.cocoapods.FlyHUD/s8SendableP":{"identifier":"doc:\/\/org.cocoapods.FlyHUD\/s8SendableP","type":"unresolvable","title":"Swift.Sendable"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/BackgroundView/initWithFrame:":{"kind":"symbol","title":"initWithFrame:","identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/BackgroundView\/initWithFrame:","abstract":[],"type":"topic","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithFrame:","kind":"identifier"}],"url":"\/documentation\/flyhud\/backgroundview\/initwithframe:","navigatorTitle":[{"text":"initWithFrame:","kind":"identifier"}]},"doc://org.cocoapods.FlyHUD/objc(pl)UIDynamicItem":{"identifier":"doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIDynamicItem","type":"unresolvable","title":"UIKit.UIDynamicItem"},"doc://org.cocoapods.FlyHUD/objc(pl)UIResponderStandardEditActions":{"identifier":"doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIResponderStandardEditActions","type":"unresolvable","title":"UIKit.UIResponderStandardEditActions"},"doc://org.cocoapods.FlyHUD/objc(pl)UIAccessibilityIdentification":{"identifier":"doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIAccessibilityIdentification","type":"unresolvable","title":"UIKit.UIAccessibilityIdentification"},"doc://org.cocoapods.FlyHUD/objc(pl)UIFocusItem":{"identifier":"doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIFocusItem","type":"unresolvable","title":"UIKit.UIFocusItem"},"doc://org.cocoapods.FlyHUD/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.FlyHUD\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/BackgroundView/commonInit()":{"title":"commonInit()","url":"\/documentation\/flyhud\/backgroundview\/commoninit()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"commonInit","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/BackgroundView\/commonInit()","kind":"symbol","abstract":[{"text":"Common initialization method.","type":"text"}],"type":"topic","role":"symbol"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/BackgroundView/intrinsicContentSize":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/BackgroundView\/intrinsicContentSize","abstract":[{"type":"text","text":"The natural size for the receiving view, considering only properties of the view itself."}],"role":"symbol","type":"topic","title":"intrinsicContentSize","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"intrinsicContentSize"},{"kind":"text","text":": "},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"}],"navigatorTitle":[{"kind":"identifier","text":"intrinsicContentSize"}],"url":"\/documentation\/flyhud\/backgroundview\/intrinsiccontentsize"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD":{"type":"topic","url":"\/documentation\/flyhud","abstract":[],"kind":"symbol","role":"collection","title":"FlyHUD","identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD"},"doc://org.cocoapods.FlyHUD/objc(pl)UIFocusEnvironment":{"identifier":"doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIFocusEnvironment","type":"unresolvable","title":"UIKit.UIFocusEnvironment"},"doc://org.cocoapods.FlyHUD/objc(pl)UIPasteConfigurationSupporting":{"identifier":"doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIPasteConfigurationSupporting","type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting"},"doc://org.cocoapods.FlyHUD/objc(pl)UILargeContentViewerItem":{"identifier":"doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UILargeContentViewerItem","type":"unresolvable","title":"UIKit.UILargeContentViewerItem"},"doc://org.cocoapods.FlyHUD/objc(pl)NSCoding":{"identifier":"doc:\/\/org.cocoapods.FlyHUD\/objc(pl)NSCoding","type":"unresolvable","title":"Foundation.NSCoding"},"doc://org.cocoapods.FlyHUD/s7CVarArgP":{"identifier":"doc:\/\/org.cocoapods.FlyHUD\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://org.cocoapods.FlyHUD/s23CustomStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.FlyHUD\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://org.cocoapods.FlyHUD/SQ":{"identifier":"doc:\/\/org.cocoapods.FlyHUD\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://org.cocoapods.FlyHUD/objc(pl)UIAppearanceContainer":{"identifier":"doc:\/\/org.cocoapods.FlyHUD\/objc(pl)UIAppearanceContainer","type":"unresolvable","title":"UIKit.UIAppearanceContainer"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"value":"BackgroundView","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"BackgroundView"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"BackgroundView"}]},{"value":[{"identifiers":["doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/BackgroundView\/intrinsicContentSize"],"title":"Instance Properties"},{"identifiers":["doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/BackgroundView\/initWithCoder:","doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/BackgroundView\/initWithFrame:","doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/BackgroundView\/layoutSubviews()"],"title":"Instance Methods"}],"path":"\/topicSections","op":"replace"},{"value":[{"title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/BaseView"],"type":"inheritsFrom","kind":"relationships"},{"identifiers":["doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ContentView"],"type":"inheritedBy","kind":"relationships","title":"Inherited By"}],"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BackgroundView"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"BaseView","identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/BaseView","preciseIdentifier":"c:@M@FlyHUD@objc(cs)BaseView"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1BackgroundView\/title","op":"replace","value":"BackgroundView"},{"value":[{"text":"BackgroundView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1BackgroundView\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1ContentView\/title","value":"ContentView","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1ContentView\/fragments","value":[{"text":"ContentView","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1BackgroundView~1layoutSubviews()\/title","value":"layoutSubviews"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"layoutSubviews"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1BackgroundView~1layoutSubviews()\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1BaseView\/title","value":"BaseView"},{"path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1BaseView\/fragments","value":[{"kind":"identifier","text":"BaseView"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1BackgroundView~1intrinsicContentSize\/title","op":"replace","value":"intrinsicContentSize"},{"value":[{"text":"intrinsicContentSize","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1BackgroundView~1intrinsicContentSize\/fragments"}]}]}