{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"override","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"draw","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"rect","kind":"internalParam"},{"kind":"text","text":": "},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"text":")","kind":"text"}]}]},{"kind":"parameters","parameters":[{"name":"rect","content":[{"inlineContent":[{"text":"The portion of the view’s bounds that needs to be updated. The first time your view is drawn, this rectangle is typically the entire","type":"text"},{"text":" ","type":"text"},{"text":"visible bounds of your view. However, during subsequent drawing operations, the rectangle may specify only part of your view.","type":"text"}],"type":"paragraph"}]}]}],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"draw","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":")"}],"title":"draw(_:)","modules":[{"name":"FlyHUD"}],"roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@FlyHUD@objc(cs)ProgressView(im)drawRect:","navigatorTitle":[{"text":"drawRect:","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD","doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ProgressView"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/flyhud\/progressview\/draw(_:)"]},{"paths":["\/documentation\/flyhud\/progressview\/draw(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ProgressView\/draw(_:)"},"sections":[],"abstract":[{"type":"text","text":"Draws the receiver’s image within the passed-in rectangle."}],"references":{"doc://org.cocoapods.FlyHUD/documentation/FlyHUD":{"type":"topic","url":"\/documentation\/flyhud","abstract":[],"kind":"symbol","role":"collection","title":"FlyHUD","identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/ProgressView":{"title":"ProgressView","url":"\/documentation\/flyhud\/progressview","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProgressView"}],"identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ProgressView","abstract":[{"type":"text","text":"A view that depicts the progress of a task over time."}],"role":"symbol","navigatorTitle":[{"text":"ProgressView","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/ProgressView/draw(_:)":{"abstract":[{"type":"text","text":"Draws the receiver’s image within the passed-in rectangle."}],"identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/ProgressView\/draw(_:)","url":"\/documentation\/flyhud\/progressview\/draw(_:)","navigatorTitle":[{"kind":"identifier","text":"drawRect:"}],"type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"draw","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CGRect","preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","title":"draw(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"drawRect:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"drawRect:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"drawRect:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"rect","kind":"internalParam"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1ProgressView\/title","value":"ProgressView"},{"value":[{"text":"ProgressView","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1ProgressView\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1ProgressView~1draw(_:)\/title","value":"drawRect:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"drawRect:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1ProgressView~1draw(_:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}