{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"BackgroundView","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"roleHeading":"Class","symbolKind":"class","navigatorTitle":[{"kind":"identifier","text":"BackgroundView"}],"externalID":"c:@M@LPHUD@objc(cs)BackgroundView","role":"symbol","title":"BackgroundView","modules":[{"name":"LPHUD"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"BackgroundView","kind":"identifier"}]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BackgroundView"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/lphud\/backgroundview"]},{"paths":["\/documentation\/lphud\/backgroundview"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BackgroundView\/color","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BackgroundView\/intrinsicContentSize","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BackgroundView\/roundedCorners","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BackgroundView\/style"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BackgroundView\/commonInit()","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BackgroundView\/layoutSubviews()"]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BaseView"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.LPHUD\/objc(pl)NSCoding","doc:\/\/org.cocoapods.LPHUD\/objc(pl)NSObject","doc:\/\/org.cocoapods.LPHUD\/objc(pl)CALayerDelegate","doc:\/\/org.cocoapods.LPHUD\/s7CVarArgP","doc:\/\/org.cocoapods.LPHUD\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.LPHUD\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.LPHUD\/SQ","doc:\/\/org.cocoapods.LPHUD\/SH","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIAccessibilityIdentification","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIAppearance","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UICoordinateSpace","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIDynamicItem","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIFocusItem","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIFocusItemContainer","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UILargeContentViewerItem","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.LPHUD\/5UIKit23UITraitChangeObservableP","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIUserActivityRestoring"]}],"references":{"doc://org.cocoapods.LPHUD/documentation/LPHUD/BackgroundView/roundedCorners":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"roundedCorners","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RoundedCorners","preciseIdentifier":"s:5LPHUD14RoundedCornersO"}],"role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BackgroundView\/roundedCorners","url":"\/documentation\/lphud\/backgroundview\/roundedcorners","abstract":[],"kind":"symbol","title":"roundedCorners"},"doc://org.cocoapods.LPHUD/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIPopoverPresentationControllerSourceItem","title":"UIKit.UIPopoverPresentationControllerSourceItem"},"doc://org.cocoapods.LPHUD/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIFocusEnvironment"},"doc://org.cocoapods.LPHUD/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIPasteConfigurationSupporting"},"doc://org.cocoapods.LPHUD/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UILargeContentViewerItem","title":"UIKit.UILargeContentViewerItem"},"doc://org.cocoapods.LPHUD/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/BackgroundView/color":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"color","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"text":"?","kind":"text"}],"role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BackgroundView\/color","url":"\/documentation\/lphud\/backgroundview\/color","abstract":[{"type":"text","text":"The background color or the blur tint color. Defaults to nil on iOS 13 and later and. UIColor(white: 0.8, alpha: 0.6) on older systems."}],"kind":"symbol","title":"color"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/BackgroundView/initWithFrame:":{"fragments":[{"kind":"text","text":"- "},{"text":"initWithFrame:","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"initWithFrame:"}],"role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BackgroundView\/initWithFrame:","url":"\/documentation\/lphud\/backgroundview\/initwithframe:","abstract":[],"kind":"symbol","title":"initWithFrame:"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/BackgroundView/layoutSubviews()":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"layoutSubviews"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"layoutSubviews","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BackgroundView\/layoutSubviews()","url":"\/documentation\/lphud\/backgroundview\/layoutsubviews()","abstract":[],"kind":"symbol","title":"layoutSubviews()"},"doc://org.cocoapods.LPHUD/objc(pl)UIResponderStandardEditActions":{"title":"UIKit.UIResponderStandardEditActions","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIResponderStandardEditActions"},"doc://org.cocoapods.LPHUD/objc(pl)CALayerDelegate":{"title":"QuartzCore.CALayerDelegate","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)CALayerDelegate"},"doc://org.cocoapods.LPHUD/objc(pl)UIFocusItem":{"title":"UIKit.UIFocusItem","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIFocusItem"},"doc://org.cocoapods.LPHUD/objc(pl)UITraitEnvironment":{"title":"UIKit.UITraitEnvironment","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UITraitEnvironment"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/BackgroundView/style":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"style","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:5LPHUD18HUDBackgroundStyleO","text":"HUDBackgroundStyle","kind":"typeIdentifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BackgroundView\/style","url":"\/documentation\/lphud\/backgroundview\/style","abstract":[{"type":"text","text":"The background style. "},{"code":"Defaults to .blur","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol","title":"style"},"doc://org.cocoapods.LPHUD/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.LPHUD\/s7CVarArgP"},"doc://org.cocoapods.LPHUD/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIUserActivityRestoring"},"doc://org.cocoapods.LPHUD/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UICoordinateSpace"},"doc://org.cocoapods.LPHUD/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIDynamicItem"},"doc://org.cocoapods.LPHUD/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.LPHUD\/SQ"},"doc://org.cocoapods.LPHUD/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.LPHUD\/s23CustomStringConvertibleP"},"doc://org.cocoapods.LPHUD/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIFocusItemContainer"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/BackgroundView/initWithCoder:":{"url":"\/documentation\/lphud\/backgroundview\/initwithcoder:","type":"topic","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BackgroundView\/initWithCoder:","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"abstract":[],"title":"initWithCoder:","kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithCoder:","kind":"identifier"}]},"doc://org.cocoapods.LPHUD/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIAppearanceContainer"},"doc://org.cocoapods.LPHUD/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","title":"UIKit.UITraitChangeObservable","identifier":"doc:\/\/org.cocoapods.LPHUD\/5UIKit23UITraitChangeObservableP"},"doc://org.cocoapods.LPHUD/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.LPHUD\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.LPHUD/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)NSObject"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/BackgroundView":{"navigatorTitle":[{"kind":"identifier","text":"BackgroundView"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BackgroundView","type":"topic","title":"BackgroundView","kind":"symbol","abstract":[],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"BackgroundView","kind":"identifier"}],"url":"\/documentation\/lphud\/backgroundview"},"doc://org.cocoapods.LPHUD/documentation/LPHUD":{"abstract":[],"kind":"symbol","title":"LPHUD","url":"\/documentation\/lphud","type":"topic","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","role":"collection"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/BackgroundView/commonInit()":{"kind":"symbol","role":"symbol","title":"commonInit()","url":"\/documentation\/lphud\/backgroundview\/commoninit()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"commonInit","kind":"identifier"},{"text":"()","kind":"text"}],"type":"topic","abstract":[{"type":"text","text":"Common initialization method, allowing overriding"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BackgroundView\/commonInit()"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/BackgroundView/intrinsicContentSize":{"navigatorTitle":[{"text":"intrinsicContentSize","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BackgroundView\/intrinsicContentSize","type":"topic","title":"intrinsicContentSize","kind":"symbol","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"intrinsicContentSize","kind":"identifier"},{"kind":"text","text":": "},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"}],"url":"\/documentation\/lphud\/backgroundview\/intrinsiccontentsize"},"doc://org.cocoapods.LPHUD/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIAppearance"},"doc://org.cocoapods.LPHUD/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.LPHUD\/SH"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/BaseView":{"kind":"symbol","role":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BaseView","title":"BaseView","navigatorTitle":[{"text":"BaseView","kind":"identifier"}],"type":"topic","url":"\/documentation\/lphud\/baseview","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseView"}]},"doc://org.cocoapods.LPHUD/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIAccessibilityIdentification"},"doc://org.cocoapods.LPHUD/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)NSCoding"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"BackgroundView"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"BackgroundView","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"BackgroundView","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BackgroundView\/intrinsicContentSize"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BackgroundView\/initWithCoder:","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BackgroundView\/initWithFrame:","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BackgroundView\/layoutSubviews()"]}]},{"path":"\/relationshipsSections","op":"replace","value":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BaseView"],"title":"Inherits From"}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"BackgroundView","kind":"identifier"},{"kind":"text","text":" : "},{"text":"BaseView","preciseIdentifier":"c:@M@LPHUD@objc(cs)BaseView","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/BaseView"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"layoutSubviews","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1BackgroundView~1layoutSubviews()\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"layoutSubviews","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1BackgroundView~1layoutSubviews()\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1BackgroundView\/title","value":"BackgroundView","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1BackgroundView\/fragments","value":[{"text":"BackgroundView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1BackgroundView~1intrinsicContentSize\/title","op":"replace","value":"intrinsicContentSize"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1BackgroundView~1intrinsicContentSize\/fragments","value":[{"kind":"identifier","text":"intrinsicContentSize"}],"op":"replace"},{"value":"BaseView","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1BaseView\/title"},{"value":[{"kind":"identifier","text":"BaseView"}],"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1BaseView\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}