{"kind":"symbol","sections":[],"metadata":{"modules":[{"name":"FlyHUD"}],"symbolKind":"method","roleHeading":"Instance Method","navigatorTitle":[{"text":"layoutSubviews","kind":"identifier"}],"title":"layoutSubviews()","externalID":"c:@M@FlyHUD@objc(cs)BackgroundView(im)layoutSubviews","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"layoutSubviews"},{"kind":"text","text":"()"}]},"identifier":{"url":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/BackgroundView\/layoutSubviews()","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD","doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/BackgroundView"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/flyhud\/backgroundview\/layoutsubviews()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/flyhud\/backgroundview\/layoutsubviews()"]}],"abstract":[{"type":"text","text":"Lays out subviews."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"override"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"layoutSubviews","kind":"identifier"},{"kind":"text","text":"()"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/BackgroundView":{"type":"topic","title":"BackgroundView","abstract":[{"type":"text","text":"The view to use as the background of the HUD."},{"type":"text","text":" "},{"type":"text","text":"HUD adds the background view as a subview behind all other views and uses its current frame location."}],"role":"symbol","url":"\/documentation\/flyhud\/backgroundview","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"BackgroundView"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"BackgroundView","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/BackgroundView"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD":{"type":"topic","url":"\/documentation\/flyhud","abstract":[],"kind":"symbol","role":"collection","title":"FlyHUD","identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD"},"doc://org.cocoapods.FlyHUD/documentation/FlyHUD/BackgroundView/layoutSubviews()":{"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"layoutSubviews"}],"title":"layoutSubviews()","url":"\/documentation\/flyhud\/backgroundview\/layoutsubviews()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"layoutSubviews"},{"kind":"text","text":"()"}],"type":"topic","abstract":[{"type":"text","text":"Lays out subviews."}],"identifier":"doc:\/\/org.cocoapods.FlyHUD\/documentation\/FlyHUD\/BackgroundView\/layoutSubviews()"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"layoutSubviews"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"layoutSubviews","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"layoutSubviews"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1BackgroundView\/title","value":"BackgroundView"},{"value":[{"text":"BackgroundView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1BackgroundView\/fragments"},{"value":"layoutSubviews","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1BackgroundView~1layoutSubviews()\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.FlyHUD~1documentation~1FlyHUD~1BackgroundView~1layoutSubviews()\/fragments","value":[{"kind":"text","text":"- "},{"text":"layoutSubviews","kind":"identifier"}],"op":"replace"}]}]}