{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"A button that is placed below the labels. Visible only if a target \/ action is added and a title is assigned.","type":"text"}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/button"},"metadata":{"roleHeading":"Instance Property","role":"symbol","title":"button","modules":[{"name":"LPHUD"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"button","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@LPHUD@objc(cs)RoundedButton","text":"RoundedButton","kind":"typeIdentifier"}],"symbolKind":"property","externalID":"s:5LPHUD3HUDC6buttonAA13RoundedButtonCvp"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"lazy"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"button"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/RoundedButton","preciseIdentifier":"c:@M@LPHUD@objc(cs)RoundedButton","text":"RoundedButton","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/lphud\/hud\/button"]}],"references":{"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUD":{"navigatorTitle":[{"kind":"identifier","text":"HUD"}],"abstract":[{"type":"text","text":"Displays a simple HUD window containing a progress indicator and two optional labels for short messages."}],"kind":"symbol","type":"topic","title":"HUD","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HUD","kind":"identifier"}],"url":"\/documentation\/lphud\/hud"},"doc://org.cocoapods.LPHUD/documentation/LPHUD":{"abstract":[],"kind":"symbol","title":"LPHUD","url":"\/documentation\/lphud","type":"topic","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","role":"collection"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/RoundedButton":{"navigatorTitle":[{"text":"RoundedButton","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/RoundedButton","url":"\/documentation\/lphud\/roundedbutton","role":"symbol","abstract":[],"type":"topic","title":"RoundedButton","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"RoundedButton","kind":"identifier"}]},"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUD/button":{"kind":"symbol","role":"symbol","url":"\/documentation\/lphud\/hud\/button","title":"button","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"button","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@LPHUD@objc(cs)RoundedButton","text":"RoundedButton","kind":"typeIdentifier"}],"type":"topic","abstract":[{"type":"text","text":"A button that is placed below the labels. Visible only if a target \/ action is added and a title is assigned."}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/button"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1HUD\/title","value":"HUD"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1HUD\/fragments","value":[{"kind":"identifier","text":"HUD"}]},{"value":"RoundedButton","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1RoundedButton\/title"},{"value":[{"kind":"identifier","text":"RoundedButton"}],"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1RoundedButton\/fragments","op":"replace"}]}]}