{"variants":[{"paths":["\/documentation\/lphud\/hud\/didmovetosuperview()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/lphud\/hud\/didmovetosuperview()"]}],"metadata":{"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didMoveToSuperview"},{"text":"()","kind":"text"}],"modules":[{"name":"LPHUD"}],"navigatorTitle":[{"text":"didMoveToSuperview","kind":"identifier"}],"title":"didMoveToSuperview()","role":"symbol","externalID":"c:@M@LPHUD@objc(cs)HUD(im)didMoveToSuperview","symbolKind":"method"},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/didMoveToSuperview()","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"didMoveToSuperview","kind":"identifier"},{"text":"()","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUD":{"navigatorTitle":[{"kind":"identifier","text":"HUD"}],"abstract":[{"type":"text","text":"Displays a simple HUD window containing a progress indicator and two optional labels for short messages."}],"kind":"symbol","type":"topic","title":"HUD","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HUD","kind":"identifier"}],"url":"\/documentation\/lphud\/hud"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUD/didMoveToSuperview()":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"didMoveToSuperview"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"didMoveToSuperview"}],"title":"didMoveToSuperview()","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/didMoveToSuperview()","type":"topic","abstract":[],"kind":"symbol","url":"\/documentation\/lphud\/hud\/didmovetosuperview()","role":"symbol"},"doc://org.cocoapods.LPHUD/documentation/LPHUD":{"abstract":[],"kind":"symbol","title":"LPHUD","url":"\/documentation\/lphud","type":"topic","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"didMoveToSuperview","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"didMoveToSuperview","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"text":"didMoveToSuperview","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1HUD\/title","value":"HUD"},{"value":[{"text":"HUD","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1HUD\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1HUD~1didMoveToSuperview()\/title","value":"didMoveToSuperview"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"didMoveToSuperview"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1HUD~1didMoveToSuperview()\/fragments"}]}]}