{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView"]]},"identifier":{"url":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView\/draw(_:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"draw","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"rect"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The portion of the view’s bounds that needs to be updated. The first time your view is drawn, this rectangle is typically the entire"},{"type":"text","text":" "},{"text":"visible bounds of your view. However, during subsequent drawing operations, the rectangle may specify only part of your view.","type":"text"}]}],"name":"rect"}],"kind":"parameters"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","sections":[],"metadata":{"symbolKind":"method","externalID":"c:@M@LPHUD@objc(cs)ProgressView(im)drawRect:","navigatorTitle":[{"kind":"identifier","text":"drawRect:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"draw"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"kind":"text","text":")"}],"role":"symbol","title":"draw(_:)","modules":[{"name":"LPHUD"}],"roleHeading":"Instance Method"},"abstract":[{"type":"text","text":"Draws the receiver’s image within the passed-in rectangle."}],"variants":[{"paths":["\/documentation\/lphud\/progressview\/draw(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/lphud\/progressview\/draw(_:)"]}],"references":{"doc://org.cocoapods.LPHUD/documentation/LPHUD":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","kind":"symbol","url":"\/documentation\/lphud","title":"LPHUD","role":"collection","type":"topic","abstract":[]},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ProgressView/draw(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"draw","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView\/draw(_:)","navigatorTitle":[{"text":"drawRect:","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/lphud\/progressview\/draw(_:)","title":"draw(_:)","abstract":[{"type":"text","text":"Draws the receiver’s image within the passed-in rectangle."}],"role":"symbol"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ProgressView":{"role":"symbol","url":"\/documentation\/lphud\/progressview","kind":"symbol","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ProgressView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ProgressView","kind":"identifier"}],"abstract":[{"type":"text","text":"A view that depicts the progress of a task over time."}],"type":"topic","title":"ProgressView","navigatorTitle":[{"kind":"identifier","text":"ProgressView"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"drawRect:","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"drawRect:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"drawRect:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":") "},{"text":"rect","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"drawRect:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ProgressView~1draw(_:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"drawRect:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ProgressView~1draw(_:)\/fragments","op":"replace"},{"op":"replace","value":"ProgressView","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ProgressView\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ProgressView\/fragments","value":[{"text":"ProgressView","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}