{"metadata":{"roleHeading":"Initializer","navigatorTitle":[{"text":"initWithFrame:","kind":"identifier"}],"externalID":"c:@M@LPHUD@objc(cs)Button(im)initWithFrame:","role":"symbol","modules":[{"name":"LPHUD"}],"title":"init(frame:)","symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"frame","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"frame","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"frame","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The frame rectangle for the view, measured in points."}]}]}]}],"abstract":[{"text":"Creates a new button with the specified frame.","type":"text"}],"variants":[{"paths":["\/documentation\/lphud\/button\/init(frame:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/lphud\/button\/init(frame:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Button\/init(frame:)"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Button"]]},"sections":[],"references":{"doc://org.cocoapods.LPHUD/documentation/LPHUD":{"role":"collection","kind":"symbol","abstract":[],"title":"LPHUD","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","type":"topic","url":"\/documentation\/lphud"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/Button/init(frame:)":{"type":"topic","url":"\/documentation\/lphud\/button\/init(frame:)","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Button\/init(frame:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(frame:)","role":"symbol","navigatorTitle":[{"text":"initWithFrame:","kind":"identifier"}],"abstract":[{"text":"Creates a new button with the specified frame.","type":"text"}],"kind":"symbol"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/Button":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Button","title":"Button","navigatorTitle":[{"text":"Button","kind":"identifier"}],"url":"\/documentation\/lphud\/button","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Button","kind":"identifier"}],"abstract":[{"type":"text","text":"A control that executes your custom code in response to user interactions."}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","value":"initWithFrame:","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFrame:"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"text":"initWithFrame:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"frame"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"value":"initWithFrame:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1Button~1init(frame:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1Button~1init(frame:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithFrame:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1Button\/title","op":"replace","value":"Button"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1Button\/fragments","op":"replace","value":[{"text":"Button","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}