{"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Label"}],"title":"Label","modules":[{"name":"LPHUD"}],"roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Label"}],"externalID":"c:@M@LPHUD@objc(cs)Label","symbolKind":"class"},"kind":"symbol","topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Label\/init(fontSize:numberOfLines:textColor:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Label\/bounds","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Label\/intrinsicContentSize","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Label\/isEmptyOfText","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Label\/text"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Label","kind":"identifier"}]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Label"},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD"]]},"abstract":[{"text":"A view that displays one or more lines of informational text.","type":"text"}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.LPHUD\/objc(cs)UILabel"],"title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.LPHUD\/objc(pl)NSCoding","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUDExtended","doc:\/\/org.cocoapods.LPHUD\/objc(pl)NSObject","doc:\/\/org.cocoapods.LPHUD\/objc(pl)CALayerDelegate","doc:\/\/org.cocoapods.LPHUD\/s7CVarArgP","doc:\/\/org.cocoapods.LPHUD\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.LPHUD\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.LPHUD\/SQ","doc:\/\/org.cocoapods.LPHUD\/SH","doc:\/\/org.cocoapods.LPHUD\/s8SendableP","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIAccessibilityIdentification","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIAppearance","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIContentSizeCategoryAdjusting","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UICoordinateSpace","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIDynamicItem","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIFocusItem","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIFocusItemContainer","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UILargeContentViewerItem","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UILetterformAwareAdjusting","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.LPHUD\/5UIKit23UITraitChangeObservableP","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/lphud\/label"]},{"paths":["\/documentation\/lphud\/label"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.LPHUD/objc(pl)UIFocusItem":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIFocusItem","title":"UIKit.UIFocusItem"},"doc://org.cocoapods.LPHUD/documentation/LPHUD":{"role":"collection","kind":"symbol","abstract":[],"title":"LPHUD","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","type":"topic","url":"\/documentation\/lphud"},"doc://org.cocoapods.LPHUD/SH":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/Label/isEmptyOfText":{"title":"isEmptyOfText","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isEmptyOfText","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"abstract":[{"type":"text","text":"Whether the text displayed by the label is nil and empty."}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Label\/isEmptyOfText","kind":"symbol","role":"symbol","url":"\/documentation\/lphud\/label\/isemptyoftext"},"doc://org.cocoapods.LPHUD/objc(pl)UILetterformAwareAdjusting":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UILetterformAwareAdjusting","title":"UIKit.UILetterformAwareAdjusting","type":"unresolvable"},"doc://org.cocoapods.LPHUD/SQ":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://org.cocoapods.LPHUD/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://org.cocoapods.LPHUD/s8SendableP":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"},"doc://org.cocoapods.LPHUD/objc(pl)UIUserActivityRestoring":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring","type":"unresolvable"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/Label/text":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Label\/text","role":"symbol","url":"\/documentation\/lphud\/label\/text","kind":"symbol","title":"text","navigatorTitle":[{"text":"text","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"text","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"The text that the label displays."}],"type":"topic"},"doc://org.cocoapods.LPHUD/objc(pl)NSCoding":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)NSCoding","title":"Foundation.NSCoding"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/Label/initWithFrame:":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Label\/initWithFrame:","role":"symbol","url":"\/documentation\/lphud\/label\/initwithframe:","kind":"symbol","title":"initWithFrame:","navigatorTitle":[{"text":"initWithFrame:","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithFrame:","kind":"identifier"}],"abstract":[],"type":"topic"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUDExtended":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"HUDExtended","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUDExtended","url":"\/documentation\/lphud\/hudextended","title":"HUDExtended","abstract":[{"type":"text","text":"Protocol describing the "},{"type":"codeVoice","code":"h"},{"type":"text","text":" extension points for HUD extended types."}],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"HUDExtended"}]},"doc://org.cocoapods.LPHUD/objc(cs)UILabel":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(cs)UILabel","title":"UILabel"},"doc://org.cocoapods.LPHUD/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://org.cocoapods.LPHUD/objc(pl)UIAppearance":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIAppearance","title":"UIKit.UIAppearance"},"doc://org.cocoapods.LPHUD/objc(pl)UITraitEnvironment":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UITraitEnvironment","title":"UIKit.UITraitEnvironment"},"doc://org.cocoapods.LPHUD/objc(pl)UICoordinateSpace":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UICoordinateSpace","title":"UIKit.UICoordinateSpace"},"doc://org.cocoapods.LPHUD/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/s7CVarArgP","title":"Swift.CVarArg"},"doc://org.cocoapods.LPHUD/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding"},"doc://org.cocoapods.LPHUD/objc(pl)UIAppearanceContainer":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIAppearanceContainer","title":"UIKit.UIAppearanceContainer"},"doc://org.cocoapods.LPHUD/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://org.cocoapods.LPHUD/objc(pl)UIFocusEnvironment":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIFocusEnvironment","title":"UIKit.UIFocusEnvironment"},"doc://org.cocoapods.LPHUD/objc(pl)CALayerDelegate":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)CALayerDelegate","title":"QuartzCore.CALayerDelegate"},"doc://org.cocoapods.LPHUD/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIPopoverPresentationControllerSourceItem","title":"UIKit.UIPopoverPresentationControllerSourceItem"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/Label/intrinsicContentSize":{"title":"intrinsicContentSize","navigatorTitle":[{"kind":"identifier","text":"intrinsicContentSize"}],"role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"intrinsicContentSize"},{"kind":"text","text":": "},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Label\/intrinsicContentSize","kind":"symbol","url":"\/documentation\/lphud\/label\/intrinsiccontentsize","abstract":[{"type":"text","text":"The natural size for the receiving view, considering only properties of the view itself."}]},"doc://org.cocoapods.LPHUD/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/5UIKit23UITraitChangeObservableP","title":"UIKit.UITraitChangeObservable"},"doc://org.cocoapods.LPHUD/objc(pl)UIContentSizeCategoryAdjusting":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIContentSizeCategoryAdjusting","title":"UIKit.UIContentSizeCategoryAdjusting"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/Label":{"title":"Label","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Label","kind":"identifier"}],"role":"symbol","abstract":[{"text":"A view that displays one or more lines of informational text.","type":"text"}],"navigatorTitle":[{"text":"Label","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Label","url":"\/documentation\/lphud\/label"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/Label/bounds":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Label\/bounds","role":"symbol","url":"\/documentation\/lphud\/label\/bounds","kind":"symbol","title":"bounds","navigatorTitle":[{"kind":"identifier","text":"bounds"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bounds","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"}],"abstract":[{"type":"text","text":"The bounds rectangle, which describes the label’s location and size in its own coordinate system."}],"type":"topic"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/Label/initWithCoder:":{"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Label\/initWithCoder:","role":"symbol","url":"\/documentation\/lphud\/label\/initwithcoder:","kind":"symbol","title":"initWithCoder:","navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithCoder:","kind":"identifier"}],"abstract":[],"type":"topic"},"doc://org.cocoapods.LPHUD/objc(pl)UIPasteConfigurationSupporting":{"title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIPasteConfigurationSupporting","type":"unresolvable"},"doc://org.cocoapods.LPHUD/objc(pl)UIAccessibilityIdentification":{"title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIAccessibilityIdentification","type":"unresolvable"},"doc://org.cocoapods.LPHUD/objc(pl)UIResponderStandardEditActions":{"title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIResponderStandardEditActions","type":"unresolvable"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/Label/init(fontSize:numberOfLines:textColor:)":{"url":"\/documentation\/lphud\/label\/init(fontsize:numberoflines:textcolor:)","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Label\/init(fontSize:numberOfLines:textColor:)","kind":"symbol","abstract":[{"text":"Creates a new label.","type":"text"}],"title":"init(fontSize:numberOfLines:textColor:)","type":"topic","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fontSize"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"numberOfLines"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":", ","kind":"text"},{"text":"textColor","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"},{"text":"?)","kind":"text"}]},"doc://org.cocoapods.LPHUD/objc(pl)UILargeContentViewerItem":{"title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UILargeContentViewerItem","type":"unresolvable"},"doc://org.cocoapods.LPHUD/objc(pl)UIFocusItemContainer":{"title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIFocusItemContainer","type":"unresolvable"},"doc://org.cocoapods.LPHUD/objc(pl)UIDynamicItem":{"title":"UIKit.UIDynamicItem","identifier":"doc:\/\/org.cocoapods.LPHUD\/objc(pl)UIDynamicItem","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"value":"Label","path":"\/metadata\/title","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"Label","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"Label","kind":"identifier"}]},{"value":[{"identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Label\/bounds","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Label\/intrinsicContentSize","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Label\/text"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Label\/initWithCoder:","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/Label\/initWithFrame:"]}],"path":"\/topicSections","op":"replace"},{"op":"replace","value":[{"identifiers":["doc:\/\/org.cocoapods.LPHUD\/objc(cs)UILabel"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"Label","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"text","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1Label~1text\/title"},{"value":[{"kind":"identifier","text":"text"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1Label~1text\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1Label~1intrinsicContentSize\/title","value":"intrinsicContentSize"},{"value":[{"kind":"identifier","text":"intrinsicContentSize"}],"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1Label~1intrinsicContentSize\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1Label\/title","value":"Label"},{"value":[{"text":"Label","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1Label\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1Label~1bounds\/title","op":"replace","value":"bounds"},{"value":[{"kind":"identifier","text":"bounds"}],"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1Label~1bounds\/fragments","op":"replace"}]}]}