{"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/Mode-swift.enum\/indicator(_:)-4gqqn","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"indicator"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"style"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ActivityIndicatorView","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ActivityIndicatorView","preciseIdentifier":"c:@M@LPHUD@objc(cs)ActivityIndicatorView"},{"text":".","kind":"text"},{"text":"Style","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ActivityIndicatorView\/Style-swift.enum","preciseIdentifier":"s:5LPHUD21ActivityIndicatorViewC5StyleO","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD","text":"HUD","preciseIdentifier":"c:@M@LPHUD@objc(cs)HUD","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:5LPHUD3HUDC4ModeO","text":"Mode","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/Mode-swift.enum"}]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"A constant that specifies the style of the object to be created. See ActivityIndicatorView.Style for descriptions of the style constants.","type":"text"}]}],"name":"style"}],"kind":"parameters"},{"kind":"content","content":[{"anchor":"return-value","type":"heading","level":2,"text":"Return Value"},{"inlineContent":[{"text":"An initialized HUD.Mode constant.","type":"text"}],"type":"paragraph"}]}],"abstract":[{"type":"text","text":"Creates an activity indicator view with the specified style."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/lphud\/hud\/mode-swift.enum\/indicator(_:)-4gqqn"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"symbolKind":"method","extendedModule":"LPHUD","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"indicator","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ActivityIndicatorView","kind":"typeIdentifier","preciseIdentifier":"c:@M@LPHUD@objc(cs)ActivityIndicatorView"},{"kind":"text","text":"."},{"text":"Style","kind":"typeIdentifier","preciseIdentifier":"s:5LPHUD21ActivityIndicatorViewC5StyleO"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"HUD","preciseIdentifier":"c:@M@LPHUD@objc(cs)HUD"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:5LPHUD3HUDC4ModeO","text":"Mode"}],"externalID":"s:5LPHUD3HUDC4ModeO9indicatoryAeA21ActivityIndicatorViewC5StyleOFZ","role":"symbol","title":"indicator(_:)","modules":[{"name":"LPHUD"}],"roleHeading":"Type Method"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD","doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/Mode-swift.enum"]]},"sections":[],"references":{"doc://org.cocoapods.LPHUD/documentation/LPHUD/ActivityIndicatorView":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ActivityIndicatorView"}],"title":"ActivityIndicatorView","navigatorTitle":[{"text":"ActivityIndicatorView","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A view that shows that a task is in progress."}],"url":"\/documentation\/lphud\/activityindicatorview","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ActivityIndicatorView","role":"symbol"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUD":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HUD"}],"title":"HUD","navigatorTitle":[{"text":"HUD","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Displays a simple HUD window containing a progress indicator and two optional labels for short messages."}],"url":"\/documentation\/lphud\/hud","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD","role":"symbol"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/ActivityIndicatorView/Style-swift.enum":{"url":"\/documentation\/lphud\/activityindicatorview\/style-swift.enum","kind":"symbol","abstract":[{"text":"The visual style of the activity indicator.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/ActivityIndicatorView\/Style-swift.enum","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Style"}],"navigatorTitle":[{"text":"Style","kind":"identifier"}],"title":"ActivityIndicatorView.Style","type":"topic"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUD/Mode-swift.enum/indicator(_:)-4gqqn":{"type":"topic","title":"indicator(_:)","kind":"symbol","url":"\/documentation\/lphud\/hud\/mode-swift.enum\/indicator(_:)-4gqqn","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"indicator","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@LPHUD@objc(cs)ActivityIndicatorView","text":"ActivityIndicatorView","kind":"typeIdentifier"},{"kind":"text","text":"."},{"text":"Style","preciseIdentifier":"s:5LPHUD21ActivityIndicatorViewC5StyleO","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"HUD","preciseIdentifier":"c:@M@LPHUD@objc(cs)HUD"},{"kind":"text","text":"."},{"preciseIdentifier":"s:5LPHUD3HUDC4ModeO","text":"Mode","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Creates an activity indicator view with the specified style."}],"identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/Mode-swift.enum\/indicator(_:)-4gqqn","role":"symbol"},"doc://org.cocoapods.LPHUD/documentation/LPHUD/HUD/Mode-swift.enum":{"title":"HUD.Mode","kind":"symbol","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD\/HUD\/Mode-swift.enum","url":"\/documentation\/lphud\/hud\/mode-swift.enum","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"Mode","kind":"identifier"}],"type":"topic","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Mode"}]},"doc://org.cocoapods.LPHUD/documentation/LPHUD":{"abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/org.cocoapods.LPHUD\/documentation\/LPHUD","url":"\/documentation\/lphud","kind":"symbol","title":"LPHUD"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ActivityIndicatorView\/title","value":"ActivityIndicatorView"},{"op":"replace","value":[{"kind":"identifier","text":"ActivityIndicatorView"}],"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1ActivityIndicatorView\/fragments"},{"value":"HUD","path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1HUD\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.LPHUD~1documentation~1LPHUD~1HUD\/fragments","op":"replace","value":[{"text":"HUD","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}